- CONTRIBUTING.md
- README.md
- dozer-orchestrator/src/cli/init.rs
Signed-off-by: Chloe Kim <chloe@getdozer.io>
> chore: fixed v1 to original link

- Cargo.lock
- dozer-api/src/grpc/client_server.rs
- dozer-api/src/grpc/shared_impl/mod.rs
- dozer-api/src/grpc/typed/tests/service.rs
- dozer-ingestion/src/connectors/ethereum/helper.rs
- dozer-orchestrator/Cargo.toml
- dozer-orchestrator/src/simple/orchestrator.rs
>  fix: on_event behavior

- dozer-core/src/dag/app.rs
- dozer-orchestrator/src/pipeline/source_builder.rs
- dozer-orchestrator/src/simple/executor.rs
> fix: Ignore unused sources for pipeline

- dozer-sql/src/pipeline/builder.rs
This PR fixes two bugs:
1. When user puts empty string or just a `;` as sql in the config, dozer panics with index out of bound.
2. When user puts multiple sql statements in the config, statements other than the first one are silently ignored.
> fix: Fix sql parsing panic and statements being silently ignored

- dozer-api/protos/api.proto
- dozer-api/protos/films.proto
- dozer-api/src/generator/protoc/template/proto.tmpl
Implementation was in #623 #634
> chore: Update inline documentation

- dozer-api/src/grpc/internal/internal_pipeline_server.rs
- dozer-api/src/grpc/types_helper.rs
related [issue](https://github.com/getdozer/dozer/issues/625)
> fix: OnEvent is not propagating data in some scenarios with postgres

- .github/workflows/coverage.yaml
- .github/workflows/dozer.yaml
- .github/workflows/nightly.yaml
This is the first half. Let's see if PR comments work.
I'm cross compiling `grcov` to save the compilation time on Github Action runners.
> chore: Enable coverage on PR

- .github/workflows/release.yaml
It often doesn't fit in the JSON request body.
> fix: Don't pass commit message to BuildKite.

- dozer-ingestion/examples/postgres/main.rs
- dozer-ingestion/src/connectors/ethereum/connector.rs
- dozer-ingestion/src/connectors/ethereum/helper.rs
- dozer-ingestion/src/connectors/kafka/connector.rs
- dozer-ingestion/src/connectors/kafka/debezium/no_schema_registry.rs
- dozer-ingestion/src/connectors/kafka/debezium/schema_registry.rs
- dozer-ingestion/src/connectors/kafka/test_utils.rs
- dozer-ingestion/src/connectors/kafka/tests.rs
- dozer-ingestion/src/connectors/mod.rs
- dozer-ingestion/src/connectors/postgres/connection/validator.rs
- dozer-ingestion/src/connectors/postgres/connector.rs
- dozer-ingestion/src/connectors/postgres/schema_helper.rs
- dozer-ingestion/src/connectors/postgres/snapshotter.rs
- dozer-ingestion/src/connectors/postgres/test_utils.rs
- dozer-ingestion/src/connectors/snowflake/connection/client.rs
- dozer-ingestion/src/connectors/snowflake/connector.rs
- dozer-ingestion/src/connectors/snowflake/snapshotter.rs
- dozer-ingestion/src/connectors/snowflake/stream_consumer.rs
- dozer-ingestion/src/connectors/snowflake/tests.rs
- dozer-orchestrator/src/pipeline/connector_source.rs
- dozer-orchestrator/src/pipeline/source_builder.rs
- dozer-orchestrator/src/simple/executor.rs
> feat: Add and use table name from table info struct

- .github/ISSUE_TEMPLATE/config.yml
Signed-off-by: Dario Pizzamiglio <1150680+mediuminvader@users.noreply.github.com>
> fix: Update issue template config with parent item

- dozer-api/src/grpc/common/service.rs
- dozer-api/src/grpc/typed/helper.rs
- dozer-api/src/grpc/types_helper.rs
Addressing https://github.com/getdozer/dozer/pull/637#issuecomment-1385153809
> fix: Unify typed service `query` and `on_event` record representation

- dozer-cache/src/cache/plan/planner.rs
- dozer-sql/src/pipeline/builder.rs
> Refactor: put `pipeline_map` into `QueryContext`

- dozer-cache/src/cache/lmdb/indexer.rs
- dozer-sql/src/pipeline/aggregation/factory.rs
- dozer-sql/src/pipeline/expression/tests/execution.rs
- dozer-sql/src/pipeline/projection/factory.rs
- aggregated unnamed wildcard (e.g. SELECT COUNT(*) FROM stocks)
- QualifiedWildcard (e.g. SELECT stocks.* FROM stocks)
> feat: select wildcard

- dozer-ingestion/src/connectors/postgres/schema_helper.rs
> fix: Fix source with empty columns list validation

- dozer-types/Cargo.toml
- dozer-types/src/tests/field_serialize_test.rs
- dozer-types/src/types/field.rs
> fix: `serde_str` is needed to bincode deserialize `Decimal`

- README.md
Signed-off-by: Chloe Kim <chloe@getdozer.io>
> fix: architecture diagram

- .github/workflows/release.yaml
feat: adding commit SHA for ECR image tag for release
> feat: adding commit SHA for ECR image tag for release

- dozer-cache/src/cache/lmdb/indexer.rs
- dozer-cache/src/cache/lmdb/tests/utils.rs
> fix: Fix record delete when duplicated words are in string field

- dozer-types/Cargo.toml
- dozer-types/src/types/field.rs
> fix: Fix usage of decimal with trailing zeros in secondary index

- dozer-ingestion/src/connectors/datafusion/table_reader.rs
I didn't rebase #832 before merging and it's causing compilation failure on `main`.
> fix: Datafusion connector compilation

- README.md
Signed-off-by: Chloe Kim <chloe@getdozer.io>
> chore: add github star line

- dozer-api/protos/types.proto
- dozer-api/src/grpc/shared_impl/filter/tests.rs
- dozer-api/src/grpc/typed/tests/fake_internal_pipeline_server.rs
- dozer-api/src/grpc/types_helper.rs
- dozer-api/src/test_utils.rs
- dozer-cache/benches/cache.rs
- dozer-cache/src/cache/lmdb/cache/mod.rs
- dozer-cache/src/cache/lmdb/cache/query/tests.rs
- dozer-cache/src/cache/lmdb/tests/basic.rs
- dozer-cache/src/cache/lmdb/tests/utils.rs
- dozer-cache/src/cache/mod.rs
- dozer-orchestrator/src/pipeline/sinks.rs
- dozer-tests/src/cache_tests/film/load_database.rs
- dozer-types/src/types/mod.rs
@v3g42 Here's the versioned records from cache.
> feat: Add record version to push and pull query results

- dozer-api/protos/films.proto
- dozer-api/protos/types.proto
- dozer-api/src/generator/protoc/generator/implementation.rs
- dozer-api/src/generator/protoc/generator/mod.rs
- dozer-api/src/generator/protoc/generator/template/proto.tmpl
- dozer-api/src/generator/protoc/tests.rs
- dozer-api/src/grpc/shared_impl/filter/tests.rs
- dozer-api/src/grpc/typed/helper.rs
- dozer-api/src/grpc/typed/tests/fake_internal_pipeline_server.rs
- dozer-api/src/grpc/typed/tests/service.rs
- dozer-api/src/grpc/typed/tests/utils.rs
- dozer-api/src/grpc/types_helper.rs
- dozer-api/src/test_utils.rs
- examples/1_hypercharge_postgres/dozer-config.yaml
Common query:
Typed query:
Common on event:
Typed on event:
> feat: Return id and version in gRPC query. Include version in push events.

- dozer-ingestion/src/connectors/object_store/adapters.rs
Minor error that slipped through the cracks
> Use correct path builder for local storage

- dozer-orchestrator/src/pipeline/builder.rs
No need to `let pipeline_ref = &mut pipeline;`
> chore: refactor code

- dozer-sql/src/pipeline/expression/geo/tests/distance.rs
> fix: Add epsilon to distance test case

- dozer-sql/src/pipeline/expression/builder.rs
- dozer-sql/src/pipeline/expression/python_udf.rs
- dozer-sql/src/pipeline/expression/tests/expression_builder_test.rs
- dozer-sql/src/pipeline/planner/projection.rs
- dozer-sql/src/pipeline/projection/factory.rs
- dozer-sql/src/pipeline/selection/factory.rs
- dozer-sql/src/pipeline/selection/processor.rs
- dozer-types/src/types/field.rs
Minor changes to reduce code verbosity/complexity
> Reduce code complexity

- .github/workflows/coverage.yaml
See effect https://discord.com/channels/1047893384762773534/1061292149007732756/1078136275170754660
> fix: Discord notification on push to `main`

- .github/workflows/general.yaml
- .github/workflows/pulls.yaml
See effect https://discord.com/channels/1047893384762773534/1061292149007732756/1078146361549144095
> chore: Update discord notification format of pull requests. Also notify issue comments.

- dozer-sql/src/pipeline/expression/execution.rs
- dozer-sql/src/pipeline/product/factory.rs
Remove an unwrap from schemas map
> fix: Remove schema unwrap

- dozer-ingestion/src/connectors/snowflake/connector.rs
- dozer-ingestion/src/connectors/snowflake/schema_helper.rs
- dozer-ingestion/src/connectors/snowflake/tests.rs
- dozer-ingestion/src/test_util.rs
- dozer-ingestion/src/tests/cases/snowflake/dozer-config.yaml
- dozer-ingestion/src/tests/cases/snowflake/expectations.json
- dozer-tests/src/e2e_tests/case.rs
> fix: Fix snowflake table name validation

- dozer-ingestion/src/connectors/snowflake/connector.rs
- dozer-ingestion/src/connectors/snowflake/tests.rs
> tests: Add tests for snowflake

- Cargo.lock
- dozer-admin/Cargo.toml
- dozer-api/Cargo.toml
- dozer-cache/Cargo.toml
- dozer-core/Cargo.toml
- dozer-ingestion/Cargo.toml
- dozer-orchestrator/Cargo.toml
- dozer-sql/Cargo.toml
- dozer-storage/Cargo.toml
- dozer-tests/Cargo.toml
- dozer-tracing/Cargo.toml
- dozer-types/Cargo.toml
> chore: Prepare for v0.1.8 release

- dozer-ingestion/src/connectors/ethereum/log/connector.rs
- dozer-ingestion/src/connectors/ethereum/trace/connector.rs
- dozer-ingestion/src/connectors/files/mod.rs
- dozer-ingestion/src/connectors/grpc/connector.rs
- dozer-ingestion/src/connectors/kafka/connector.rs
- dozer-ingestion/src/connectors/mod.rs
- dozer-ingestion/src/connectors/object_store/connector.rs
- dozer-ingestion/src/connectors/postgres/connection/validator.rs
- dozer-ingestion/src/connectors/postgres/connector.rs
- dozer-ingestion/src/connectors/postgres/iterator.rs
- dozer-ingestion/src/connectors/postgres/mod.rs
- dozer-ingestion/src/connectors/postgres/replication_slot_helper.rs
- dozer-ingestion/src/connectors/postgres/replicator.rs
- dozer-ingestion/src/connectors/postgres/snapshotter.rs
- dozer-ingestion/src/connectors/postgres/test_utils.rs
- dozer-ingestion/src/connectors/postgres/tests/client.rs
- dozer-ingestion/src/connectors/postgres/tests/continue_replication_tests.rs
- dozer-ingestion/src/connectors/postgres/tests/e2e.rs
- dozer-ingestion/src/connectors/postgres/tests/mod.rs
- dozer-ingestion/src/connectors/postgres/xlog_mapper.rs
- dozer-ingestion/src/connectors/snowflake/connector.rs
- dozer-ingestion/src/errors.rs
- dozer-ingestion/src/ingestion/ingestor.rs
- dozer-orchestrator/src/pipeline/connector_source.rs
- dozer-types/src/ingestion_types.rs
> feat: Implement start from in postgres connector

- Cargo.lock
- dozer-api/Cargo.toml
- dozer-api/src/errors.rs
- dozer-api/src/grpc/client_server.rs
- dozer-api/src/grpc/common/service.rs
- dozer-api/src/grpc/typed/service.rs
- dozer-api/src/grpc/typed/tests/service.rs
- dozer-api/src/lib.rs
- dozer-api/src/rest/api_generator.rs
- dozer-api/src/rest/mod.rs
- dozer-api/src/rest/tests/auth.rs
- dozer-api/src/rest/tests/routes.rs
- dozer-api/src/test_utils.rs
- dozer-cache/src/reader.rs
- dozer-ingestion/src/connectors/postgres/replication_slot_helper.rs
- dozer-orchestrator/src/errors.rs
- dozer-orchestrator/src/simple/orchestrator.rs
This is for handling the `AliasCreated` message, which is yet to be
sent from app server.
> feat: Add `RoCacheEndpoint::redirect_cache`.

- dozer-sql/src/pipeline/planner/projection.rs
> fix: select * wildcard

- Cargo.lock
- dozer-ingestion/Cargo.toml
- dozer-ingestion/src/connectors/postgres/helper.rs
- dozer-ingestion/src/errors.rs
- dozer-types/Cargo.toml
> fix: Fix convert from jsonb to dozer type

- dozer-sql/src/pipeline/expression.rs
- dozer-sql/src/pipeline/expression/builder.rs
- dozer-sql/src/pipeline/expression/comparison.rs
- dozer-sql/src/pipeline/expression/datetime.rs
- dozer-sql/src/pipeline/expression/execution.rs
- dozer-sql/src/pipeline/expression/mathematical.rs
- dozer-sql/src/pipeline/expression/scalar/tests.rs
- dozer-sql/src/pipeline/expression/scalar/tests/cast.rs
- dozer-sql/src/pipeline/expression/scalar/tests/datetime.rs
> feat: DAY_OF_WEEK() + SQL extensive type support for operations

- dozer-ingestion/src/connectors/mod.rs
- dozer-ingestion/src/connectors/postgres/connection/validator.rs
- dozer-ingestion/src/connectors/postgres/connector.rs
- dozer-ingestion/src/connectors/postgres/mod.rs
- dozer-ingestion/src/connectors/postgres/schema/helper.rs
- dozer-ingestion/src/connectors/postgres/schema/mod.rs
- dozer-ingestion/src/connectors/postgres/schema/tests.rs
- dozer-ingestion/src/connectors/postgres/snapshotter.rs
- dozer-ingestion/src/connectors/postgres/test_utils.rs
- dozer-ingestion/src/connectors/postgres/tests/client.rs
- dozer-ingestion/src/errors.rs
> fix: Fix check of supported tables in postgres

- .github/workflows/coverage.yaml
This change will remove android library from runner to increase free space size
> chore: Add remove unnecessary libraries remove

- dozer-ingestion/src/connectors/postgres/schema/helper.rs
- dozer-ingestion/src/connectors/postgres/test_utils.rs
- dozer-ingestion/src/connectors/postgres/tests/client.rs
- dozer-ingestion/src/connectors/postgres/tests/continue_replication_tests.rs
- dozer-ingestion/src/test_util.rs
Fixes #1073
In this PR, I have simplified select query by removing unnecessary join and subselect. It also improves query speed.
> refactor: Simplify schemas fetch query

- .github/workflows/release.yaml
Tested with Action run https://github.com/getdozer/dozer/actions/runs/4315153098/jobs/7529135614 and https://github.com/getdozer/dozer/actions/runs/4315230422/jobs/7529320238
> chore: Fix docker image publishing steps in release workflow

- dozer-ingestion/Cargo.toml
- dozer-ingestion/benches/connectors.rs
- dozer-ingestion/benches/grpc.rs
- dozer-ingestion/benches/grpc.yaml
- dozer-ingestion/benches/helper.rs
- dozer-ingestion/src/connectors/grpc/adapter/arrow.rs
- dozer-ingestion/src/connectors/grpc/adapter/mod.rs
- dozer-ingestion/src/connectors/grpc/tests.rs
- dozer-ingestion/src/connectors/postgres/connection/validator.rs
- dozer-ingestion/src/connectors/postgres/replication_slot_helper.rs
- dozer-ingestion/src/connectors/postgres/snapshotter.rs
- dozer-types/src/arrow_types/errors.rs
- dozer-types/src/arrow_types/from_arrow.rs
Arrow df was not setting the right schema_id
> fix: Ingestion via Arrow

- dozer-storage/src/lib.rs
- dozer-storage/src/lmdb_database/lmdb_val.rs
- dozer-storage/src/lmdb_database/mod.rs
- dozer-storage/src/lmdb_map.rs
> feat: Add `LmdbMap`

- dozer-storage/src/lib.rs
- dozer-storage/src/lmdb_database/lmdb_val.rs
- dozer-storage/src/lmdb_database/mod.rs
- dozer-storage/src/lmdb_map.rs
- dozer-storage/src/lmdb_multimap.rs
> feat: Add `LmdbMultimap`

- Cargo.lock
- dozer-sql/Cargo.toml
- dozer-tests/Cargo.toml
- dozer-tests/src/sql_tests/mapper.rs
Close https://github.com/getdozer/dozer/pull/1032
> chore: bump sqlparser v0.31.0

- dozer-ingestion/benches/connectors.rs
- dozer-ingestion/benches/grpc.rs
- dozer-sql/src/pipeline/errors.rs
- dozer-sql/src/pipeline/expression/comparison.rs
- dozer-sql/src/pipeline/expression/logical.rs
- dozer-sql/src/pipeline/expression/mathematical.rs
- dozer-types/src/types/mod.rs
> refactor: comparison errors

- dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs
- dozer-cache/src/cache/lmdb/cache/main_environment/operation_log/mod.rs
- dozer-cache/src/cache/lmdb/cache/mod.rs
- dozer-cache/src/cache/lmdb/cache/secondary_environment/comparator.rs
- dozer-cache/src/cache/lmdb/cache/secondary_environment/mod.rs
- dozer-cache/src/cache/lmdb/cache_manager.rs
- dozer-cache/src/cache/lmdb/indexing.rs
- dozer-cache/src/cache/lmdb/tests/read_write.rs
- dozer-cache/src/cache/lmdb/tests/utils.rs
- dozer-cache/src/cache/lmdb/utils.rs
> fix: Lmdb environments should use the same map size

- Cargo.lock
- dozer-tests/Cargo.toml
- dozer-tests/src/sqllogictest/README.md
- dozer-tests/src/sqllogictest/src/arg.rs
- dozer-tests/src/sqllogictest/src/error.rs
- dozer-tests/src/sqllogictest/src/main.rs
- dozer-tests/src/sqllogictest/src/sql_tests/helper.rs
- dozer-tests/src/sqllogictest/src/sql_tests/mapper.rs
- dozer-tests/src/sqllogictest/src/sql_tests/mod.rs
- dozer-tests/src/sqllogictest/src/sql_tests/pipeline.rs
- dozer-tests/src/sqllogictest/src/validator.rs
- dozer-tests/src/sqllogictest/suits/agg.test
- dozer-tests/src/sqllogictest/suits/example.test
- dozer-tests/src/sqllogictest/suits/join.test
- dozer-tests/src/sqllogictest/suits/nested.test
- dozer-tests/src/sqllogictest/suits/simple.test
- dozer-tests/src/sqllogictest/suits/union.test
Introduce sqllogictest for dozer, make it more flexible to add massive tests.
Ideally, the test set of sqlite can be reused later!
> feat: introduce sqllogictest for dozer

- dozer-ingestion/README.md
- dozer-ingestion/SPEC.md
- dozer-ingestion/src/connectors/mod.rs
- dozer-ingestion/src/ingestion/ingestor.rs
- dozer-types/src/ingestion_types.rs
- dozer-types/src/node.rs
- dozer-types/src/types/field.rs
- dozer-types/src/types/mod.rs
> chore: Add specification for connectors

- dozer-cache/src/cache/lmdb/cache/main_environment/operation_log/mod.rs
- dozer-ingestion/benches/helper.rs
- dozer-sql/src/pipeline/aggregation/avg.rs
- dozer-sql/src/pipeline/aggregation/max.rs
- dozer-sql/src/pipeline/aggregation/min.rs
- dozer-sql/src/pipeline/aggregation/sum.rs
- dozer-sql/src/pipeline/aggregation/tests/aggregation_avg_tests.rs
> refactor: average

- dozer-cache/src/cache/lmdb/indexing.rs
- dozer-cache/src/errors.rs
- dozer-core/src/errors.rs
- dozer-orchestrator/src/pipeline/sinks.rs
Added a new `SinkError` variant `CacheFull`. The error message looks like
```text
Cache test has reached its maximum size. Try to increase `cache_max_map_size` in the config.
```
> chore: Hint `cache_max_map_size` config in error message

- dozer-api/src/test_utils.rs
- dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs
- dozer-cache/src/cache/lmdb/cache/main_environment/operation_log/mod.rs
- dozer-cache/src/cache/lmdb/cache/mod.rs
- dozer-cache/src/cache/lmdb/cache_manager.rs
- dozer-cache/src/cache/lmdb/tests/basic.rs
- dozer-cache/src/cache/lmdb/tests/read_write.rs
- dozer-cache/src/cache/lmdb/tests/utils.rs
- dozer-cache/src/cache/mod.rs
- dozer-cache/src/lib.rs
- dozer-core/src/executor.rs
- dozer-core/src/executor/processor_node.rs
- dozer-orchestrator/src/pipeline/conflict_resolver.rs
- dozer-orchestrator/src/pipeline/mod.rs
- dozer-orchestrator/src/pipeline/sinks.rs
- dozer-orchestrator/src/pipeline/tests/conflict_resolution_tests.rs
- dozer-orchestrator/src/pipeline/tests/mod.rs
- dozer-orchestrator/src/test_utils.rs
- dozer-tests/src/cache_tests/film/load_database.rs
- dozer-tests/src/sql_tests/mapper.rs
- dozer-types/src/models/api_endpoint.rs
Processor and sink error handling implementation for #1224 . Based on discussion - https://github.com/getdozer/dozer/discussions/1237
> feat: Resolve sink errors

- dozer-api/src/grpc/client_server.rs
- dozer-api/src/grpc/typed/helper.rs
- dozer-api/src/grpc/typed/service.rs
- dozer-api/src/grpc/typed/tests/utils.rs
> feature: Handle grpc API errors gracefully

- dozer-ingestion/src/connectors/postgres/schema/helper.rs
Every new table in postgres database has a replication identity set to "default", meaning the replication stream will send PK in row update message. Suppose there is no PK and replication identity is "default". In that case, postgres will not allow updating or deleting rows so that dozer can read initial snapshot and later it will receive only insert messages.
In this case, postgres table without PK and with "default" identity would work only as append-only data source.
> fix: Use cdc type "nothing" when no PK defined

- dozer-api/README.md
- dozer-types/protos/types.proto
> doc: Add type conversion spec in API

- Cargo.lock
- dozer-ingestion/Cargo.toml
- dozer-ingestion/tests/test_connectors.rs
- dozer-ingestion/tests/test_suite/basic.rs
- dozer-ingestion/tests/test_suite/connectors/arrow.rs
- dozer-ingestion/tests/test_suite/connectors/object_store/local_storage.rs
- dozer-ingestion/tests/test_suite/connectors/postgres.rs
- dozer-ingestion/tests/test_suite/connectors/sql.rs
- dozer-ingestion/tests/test_suite/data.rs
- dozer-ingestion/tests/test_suite/mod.rs
- dozer-ingestion/tests/test_suite/records.rs
- dozer-sql/src/pipeline/expression/scalar/tests/comparison.rs
`CudConnectorTest` allows a connector test to send operations to connector and validates if the final state is consistent.
> test: Add cud test suite and implement for postgres

- dozer-api/src/lib.rs
- dozer-api/src/test_utils.rs
- dozer-cache/benches/cache.rs
- dozer-cache/src/cache/lmdb/cache_manager.rs
- dozer-cache/src/cache/mod.rs
- dozer-orchestrator/src/errors.rs
- dozer-orchestrator/src/lib.rs
- dozer-orchestrator/src/pipeline/builder.rs
- dozer-orchestrator/src/pipeline/sinks.rs
- dozer-orchestrator/src/simple/executor.rs
- dozer-orchestrator/src/simple/orchestrator.rs
- dozer-orchestrator/src/test_utils.rs
- dozer-tests/src/cache_tests/film/load_database.rs
Otherwise it can't be used on read only filesystem
> fix: Api should use read only cache manager

- .github/workflows/integration.yaml
@mediuminvader I need this to be merged to begin testing, otherwise it won't show on Github Actions UI.
> test: Add integration test on Github runner

- dozer-api/src/grpc/client_server.rs
Closes [#1292](https://github.com/getdozer/dozer/issues/1292)
> fix: Fix web config usage in auth grpc service

- dozer-orchestrator/Cargo.toml
> chore: Remove protobuf dependency from deb

- dozer-api/src/generator/oapi/utils.rs
- dozer-api/src/generator/protoc/generator/implementation.rs
fix: grpc error caused by duration
> fix: grpc error caused by duration

- dozer-admin/src/server.rs
- dozer-admin/src/services/application_service.rs
- dozer-api/src/cache_builder/mod.rs
- dozer-api/src/grpc/client_server.rs
- dozer-api/src/lib.rs
- dozer-api/src/rest/mod.rs
- dozer-orchestrator/src/lib.rs
- dozer-orchestrator/src/main.rs
- dozer-orchestrator/src/shutdown.rs
- dozer-orchestrator/src/simple/orchestrator.rs
- dozer-tests/src/tests/e2e/mod.rs
> fix: Api thread graceful shutdown

- dozer-cache/src/cache/lmdb/cache/main_environment/conflict_resolution_tests.rs
- dozer-ingestion/src/errors.rs
> fix: Use proper error message for postgres replication slot creation

- dozer-orchestrator/src/errors.rs
- dozer-orchestrator/src/simple/orchestrator.rs
- dozer-orchestrator/src/simple/schemas.rs
- dozer-orchestrator/src/utils.rs
```text
pipeline/schemas.json
pipeline/logs/trips
```
```text
pipeline/logs/trips/schema.json
pipeline/logs/trips/log
```
> refactor: Store schema of sinks separately

- .github/workflows/release.yaml
> chore: Add deb generation to release process

- dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs
To summarize the cache insert/update/delete strategy:
- If schema is append only, insert always succeeds, update and delete are not allowed.
- If primary index is not empty, conflict is determined by the record primary key. The current behaviour is that only the first inserted record can be queried using primary key, though all records can be queried using secondary indexes. This is more of an accidental result as the implementation evolves to its current status, rather than a carefully designed feature.
- If schema is not append only, update and delete are allowed.
- If primary index is empty, insert always succeeds, update and delete conflicts are determined by record hash.
- If primary index is not empty, all conflicts are determined by the record primary key.
> refactor: Don't check for insert conflict when schema has no primary key

- dozer-orchestrator/src/cli/types.rs
- dozer-orchestrator/src/errors.rs
- dozer-orchestrator/src/lib.rs
- dozer-orchestrator/src/main.rs
- dozer-orchestrator/src/simple/orchestrator.rs
- dozer-types/build.rs
`dozer deploy <target_url> [-u <username> -p <password>] [-c <config_path>]`
default `target_url`: `cloud.getdozer.io`
> feat: `dozer deploy` command

- dozer-ingestion/src/connectors/snowflake/connection/client.rs
- dozer-ingestion/src/connectors/snowflake/schema_helper.rs
- dozer-orchestrator/src/cli/init.rs
- dozer-types/src/ingestion_types.rs
Add custom snowflake role support
Add default type mapping for variant and time field
Fix table schema retrival from PUBLIC schema
Update snowflake schema sample
> Snowflake connector fixes

- dozer-cache/src/cache/lmdb/tests/basic.rs
> chore: Recover `update_record_when_primary_changes` test

- dozer-api/src/generator/protoc/generator/implementation.rs
- dozer-api/src/generator/protoc/generator/mod.rs
- dozer-api/src/generator/protoc/tests.rs
- dozer-api/src/lib.rs
- dozer-log-js/src/lib.rs
- dozer-log-python/src/lib.rs
- dozer-log/src/errors.rs
- dozer-log/src/home_dir.rs
- dozer-log/src/schemas.rs
- dozer-orchestrator/src/errors.rs
- dozer-orchestrator/src/lib.rs
- dozer-orchestrator/src/simple/migration.rs
- dozer-orchestrator/src/simple/mod.rs
- dozer-orchestrator/src/simple/orchestrator.rs
> feat: Run migration only when necessary

- dozer-api/src/generator/protoc/generator/implementation.rs
- dozer-api/src/generator/protoc/generator/mod.rs
- dozer-api/src/generator/protoc/tests.rs
- dozer-api/src/lib.rs
- dozer-log-js/src/lib.rs
- dozer-log-python/src/lib.rs
- dozer-log/src/errors.rs
- dozer-log/src/home_dir.rs
- dozer-log/src/schemas.rs
- dozer-orchestrator/src/errors.rs
- dozer-orchestrator/src/lib.rs
- dozer-orchestrator/src/simple/migration.rs
- dozer-orchestrator/src/simple/mod.rs
- dozer-orchestrator/src/simple/orchestrator.rs
…24)"
This reverts commit 7e2e371ad18f6fa800528aa0bcf2ddb0d2bcae51.
> chore: Recover "feat: Run migration only when necessary (#1515)"

- dozer-api/src/errors.rs
- dozer-api/src/lib.rs
- dozer-api/src/test_utils.rs
- dozer-log/src/home_dir.rs
- dozer-types/src/models/api_endpoint.rs
> feat: Allow starting API on selected migration number

- dozer-api/src/cache_builder/mod.rs
- dozer-api/src/errors.rs
- dozer-api/src/generator/protoc/tests.rs
- dozer-api/src/lib.rs
- dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs
- dozer-cache/src/cache/lmdb/cache/mod.rs
- dozer-cache/src/cache/lmdb/tests/basic.rs
- dozer-cache/src/cache/mod.rs
- dozer-cache/src/errors.rs
- dozer-log-js/src/lib.rs
- dozer-log-python/src/lib.rs
- dozer-log/src/reader.rs
- dozer-log/src/schemas.rs
- dozer-orchestrator/src/lib.rs
- dozer-orchestrator/src/simple/migration.rs
- dozer-orchestrator/src/simple/orchestrator.rs
> feat: Api server can continue cache building from checkpoint

- .github/ISSUE_TEMPLATE/documentation_improvement.md
- Create documentation_improvement.md issue template
May the dozer be with you ✨
> Add issue template for dozer documentation improvement 

- dozer-orchestrator/src/simple/cloud.rs
I'm not sure if this is what the `cloud update` experience is expected to be. @karolisg?
> chore: Call `start_dozer` on `dozer cloud update`

- dozer-orchestrator/src/simple/cloud_orchestrator.rs
- dozer-types/protos/cloud.proto
Looks like this 
```text
+--------------+-----------------------------------------+
| Api endpoint | http://192.168.49.2                     |
+--------------+-----------------------------------------+
| Revisions    | +----------+-----+-----+--------------+ |
|              | | Revision | App | Api | Version      | |
|              | +==========+=====+=====+==============+ |
|              | | 0        | ✅︎  | ✅︎  |              | |
|              | +----------+-----+-----+--------------+ |
|              | | 1        | ✅︎  | ✅︎  | v1 (current) | |
|              | +----------+-----+-----+--------------+ |
+--------------+-----------------------------------------+
```
> feat: Show revision and version information in `cloud status`

- Cargo.lock
- dozer-orchestrator/Cargo.toml
- dozer-orchestrator/src/simple/orchestrator.rs
- dozer-tracing/Cargo.toml
- dozer-tracing/src/telemetry.rs
Tested by pushing to `release-dev` and launch the image on minikube. Works fine.
> chore: Don't show progress bar or log color when not outputting to tty

- Cargo.lock
- dozer-cli/Cargo.toml
- dozer-cli/src/errors.rs
- dozer-cli/src/simple/cloud/version.rs
- dozer-cli/src/simple/cloud_orchestrator.rs
We should merge #1600 before this
> chore: Show status of all api servers

- dozer-api/src/lib.rs
- dozer-cache/src/cache/lmdb/cache/main_environment/conflict_resolution_tests.rs
- dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs
- dozer-types/src/models/api_endpoint.rs
I changed the prost enumeration to oneof because less code is needed.
> fix: `ApiEndpoint::conflict_resolution` and `ApiEndpoint::version` was not serialized

- dozer-ingestion/src/connectors/kafka/connector.rs
- dozer-ingestion/src/connectors/kafka/debezium/schema_registry.rs
- dozer-ingestion/src/connectors/kafka/mod.rs
- dozer-ingestion/src/connectors/kafka/no_schema_registry_basic.rs
- dozer-ingestion/src/connectors/kafka/stream_consumer_basic.rs
- dozer-ingestion/src/errors.rs
Closes https://github.com/getdozer/dozer/pull/1626
> feat: Allow use kafka without schema registry

- dozer-ingestion/src/connectors/postgres/helper.rs
text[], varchar[], char[], bpchar[] support
> feat: _text

- dozer-api/src/cache_builder/mod.rs
Probably not so reasonable because we didn't take account into when the log was generated.
When a API server starts later, the data latency will be really big.
> feat: Add data latency metrics.

- dozer-sql/src/pipeline/expression/builder.rs
- dozer-sql/src/pipeline/expression/case.rs
- dozer-sql/src/pipeline/expression/execution.rs
- dozer-sql/src/pipeline/expression/mod.rs
- dozer-sql/src/pipeline/expression/tests/case.rs
- dozer-sql/src/pipeline/expression/tests/mod.rs
```sql
CASE
WHEN condition1 THEN result1
WHEN condition2 THEN result2
WHEN conditionN THEN resultN
ELSE result
END
```
> feat: CASE statement

- dozer-types/protos/cloud.proto
This reverts commit 94136c1d03cac7eb14f7376f81b63fc87d14a0c4.
> Revert "chore: enhance response for UI render (#1648)"

- dozer-cli/src/simple/orchestrator.rs
- dozer-log/src/storage/mod.rs
> fix: Properly log error when internal pipeline server can't be started

- dozer-types/src/types/mod.rs
Looks like this
```
+-----------------+---------+----------+------+
| Field           | Type    | Nullable | PK   |
+-----------------+---------+----------+------+
| company_id      | String  | false    | true |
+-----------------+---------+----------+------+
| company_name    | String  | false    | true |
+-----------------+---------+----------+------+
| company_ad      | Json    | true     | true |
+-----------------+---------+----------+------+
| company_website | String  | true     | true |
+-----------------+---------+----------+------+
| remarks         | String  | true     | true |
+-----------------+---------+----------+------+
| company_product | Json    | true     | true |
+-----------------+---------+----------+------+
| is_for_ad       | Boolean | false    | true | …
```
> chore: Print in the schema if a field is primary key

- dozer-sql/src/pipeline/expression/builder.rs
- dozer-sql/src/pipeline/expression/execution.rs
- dozer-sql/src/pipeline/expression/in_list.rs
- dozer-sql/src/pipeline/expression/mod.rs
- dozer-sql/src/pipeline/expression/tests/in_list.rs
- dozer-sql/src/pipeline/expression/tests/logical.rs
- dozer-sql/src/pipeline/expression/tests/mod.rs
part of https://github.com/getdozer/dozer/issues/1659
Support InList clause in streaming SQL. This is only for InList, we also need to support the InSubquery.
> feat: support InList clause in streaming SQL

- dozer-api/src/api_helper.rs
- dozer-api/src/cache_builder/mod.rs
- dozer-api/src/grpc/metric_middleware.rs
- dozer-api/src/lib.rs
- dozer-api/src/rest/rest_metric_middleware.rs
- dozer-cli/src/simple/orchestrator.rs
- dozer-core/src/executor/sink_node.rs
- dozer-sql/src/pipeline/product/join/processor.rs
- dozer-tracing/src/lib.rs
- dozer-tracing/src/telemetry.rs
This reverts commit 3a0b1ace362e4c03226eba4774c69f1368171a7a.
> Revert "chore: set bucket for histogram (#1723)"

- .github/workflows/release.yaml
chore: edit kafka feature with snowflake docker image release flow
> chore: edit kafka feature with snowflake docker image release flow

- dozer-api/src/errors.rs
- dozer-cache/src/cache/lmdb/cache/main_environment/conflict_resolution_tests.rs
- dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs
- dozer-cache/src/errors.rs
- dozer-cli/src/errors.rs
- dozer-cli/src/simple/orchestrator.rs
- dozer-log/src/reader.rs
- dozer-log/src/replication/mod.rs
The fix is actually three lines: https://github.com/getdozer/dozer/pull/1750/files#diff-c053b9b8a657e13414a9824c59f11675d93d9ca223f32cecd55e59fc1ca1731dR196
Other changes are enhanced error and log information.
> fix: Log reader was duplicating records that were persisted

- dozer-cli/src/pipeline/builder.rs
- dozer-cli/src/ui_helper.rs
Emit SQL Graph to monitor pipeline & join metrics
> feat: emit sql graph

- dozer-api/src/cache_builder/mod.rs
Example:
```text
cache_operation{endpoint="trips_data",migration="v0003",operation_type="insert",snapshotting="true"} 126447
```
The label is either "true" or "false".
> feat: Add new label snapshotting to cache_operation metric

- dozer-sql/src/pipeline/product/mod.rs
- dozer-sql/src/pipeline/product/tests/mod.rs
- dozer-sql/src/pipeline/product/tests/pipeline_test.rs
- dozer-sql/src/pipeline/table_operator/tests/pipeline_test.rs
- dozer-sql/src/pipeline/window/mod.rs
- dozer-sql/src/pipeline/window/tests/mod.rs
- dozer-sql/src/pipeline/window/tests/pipeline_test.rs
Fixes #1063 
Removed duplicate types TestSink and TestSinkFactory
> test: Removed duplicate types

- dozer-core/src/processor_record.rs
- dozer-sql/src/pipeline/errors.rs
- dozer-sql/src/pipeline/product/join/operator.rs
- dozer-sql/src/pipeline/product/join/processor.rs
- dozer-sql/src/pipeline/projection/processor.rs
- dozer-sql/src/pipeline/table_operator/factory.rs
- dozer-sql/src/pipeline/table_operator/lifetime.rs
- dozer-sql/src/pipeline/table_operator/tests/operator_test.rs
- dozer-types/src/types/mod.rs
Size/alignment in bytes goes from 64/16 to 32/8
> perf: Optimize memory usage for `Lifetime`

- dozer-cli/src/cli/helper.rs
- dozer-cli/src/lib.rs
- dozer-cli/src/main.rs
- dozer-cli/src/simple/orchestrator.rs
- dozer-tests/src/tests/e2e/mod.rs
It's only implemented by `SimpleOrchestrator`
> chore: Remove unused `Orchestrator` trait

- dozer-core/src/processor_record.rs
- dozer-ingestion/src/connectors/postgres/helper.rs
- dozer-ingestion/src/connectors/postgres/schema/helper.rs
- dozer-ingestion/src/connectors/postgres/xlog_mapper.rs
- dozer-sql/src/pipeline/expression/conditional.rs
fix: custom enum row detection, support different type Coalesce
> fix: custom enum row detection, support different type Coalesce

- Cargo.lock
- dozer-api/src/grpc/types_helper.rs
- dozer-api/src/lib.rs
- dozer-cli/Cargo.toml
- dozer-cli/src/cli/types.rs
- dozer-cli/src/errors.rs
- dozer-cli/src/lib.rs
- dozer-cli/src/live/errors.rs
- dozer-cli/src/live/helper.rs
- dozer-cli/src/live/mod.rs
- dozer-cli/src/live/server.rs
- dozer-cli/src/live/state.rs
- dozer-cli/src/live/watcher.rs
- dozer-cli/src/main.rs
- dozer-sql/src/pipeline/builder.rs
- dozer-sql/src/pipeline/errors.rs
- dozer-types/build.rs
- dozer-types/protos/live.proto
- dozer-types/src/grpc_types.rs
Expose 
- Hot reloading to generate schemas and graphs for sources and endpoints
- API explorer experience
> feat: implement live code reload experience. 

- dozer-api/src/grpc/internal/internal_pipeline_server.rs
- dozer-types/protos/internal.proto
> feat: Add `list_endpoints` to internal server

- Cargo.lock
- dozer-cli/Cargo.toml
- dozer-cli/src/live/downloader.rs
- dozer-cli/src/live/errors.rs
- dozer-cli/src/live/mod.rs
If dozer-live ui is not present on local or updated then download and use latest dozer-live ui.
> feat: dowload and use dozer-live ui

- dozer-log/src/replication/mod.rs
Bug happens in following senario:
1. App and api both runs and one operation is ingested. At this time, the operation is not persisted to log, because there's only one operation and it doesn't reach the persisting threshold. The operation is persisted to cache because api gets the operation from app gRPC stream.
2. App and api restarts and another operation is ingested. This operation will be seen by the app, but api will ignore this operation, because app believes this is the first operation, while api is only interested in the second operation and so on.
We fix this by including a "marker" file in the log directory, so app knows that the log may contain unpersisted operations and create a new log.
This is a temporary workaround. We need to solve app/api persistence mismatch properly …
> fix: Mark log creation to avoid writing to old log version

- Cargo.lock
- dozer-core/src/error_manager.rs
- dozer-tracing/Cargo.toml
- dozer-tracing/src/telemetry.rs
- dozer-types/src/models/app_config.rs
- dozer-types/src/models/telemetry.rs
https://aws-otel.github.io/docs/introduction
> feat: replace jaeger with xray by using ADOT

- dozer-cli/src/live/state.rs
- dozer-cli/src/main.rs
- dozer-cli/src/pipeline/builder.rs
- dozer-cli/src/pipeline/connector_source.rs
- dozer-cli/src/pipeline/source_builder.rs
- dozer-cli/src/pipeline/tests/builder.rs
- dozer-cli/src/simple/executor.rs
- dozer-cli/src/simple/orchestrator.rs
- dozer-core/src/executor/mod.rs
- dozer-ingestion/src/connectors/object_store/adapters.rs
- dozer-ingestion/src/connectors/object_store/connector.rs
- dozer-ingestion/src/connectors/object_store/csv/csv_table.rs
- dozer-ingestion/src/connectors/object_store/parquet/parquet_table.rs
- dozer-ingestion/src/ingestion/mod.rs
- dozer-ingestion/tests/test_suite/basic.rs
Join on the source sender thread, abort the connector future on shutdown, and fix a rather nasty deadlock in `ConnectorSource`
> Wait for connectors to stop on shutdown

- dozer-ingestion/src/connectors/postgres/snapshotter.rs
Don't panic when the receiver goes away and make sure all snapshotting tasks are cancelled when shutting down.
> Clean up postgres snapshotter

- Cargo.lock
- dozer-cli/src/errors.rs
- dozer-cli/src/live/mod.rs
- dozer-cli/src/live/progress.rs
- dozer-cli/src/live/server.rs
- dozer-cli/src/live/state.rs
- dozer-cli/src/live/watcher.rs
- dozer-cli/src/pipeline/builder.rs
- dozer-cli/src/ui_helper.rs
- dozer-types/protos/live.proto
- Broadcasts start, success and failure of build
- Removed recursive watching (This was causing `.dozer` and `target` folders to trigger build)
> fix: introduce build states and fix inconsistencies

- dozer-ingestion/src/connectors/mysql/binlog.rs
- dozer-ingestion/src/connectors/mysql/connector.rs
- dozer-ingestion/src/connectors/mysql/conversion.rs
- dozer-ingestion/src/connectors/mysql/helpers.rs
- dozer-ingestion/src/connectors/mysql/mod.rs
- dozer-ingestion/src/connectors/mysql/schema.rs
- dozer-ingestion/src/connectors/mysql/tests.rs
- dozer-ingestion/src/errors.rs
- dozer-ingestion/src/tests/connections/mysql/docker-compose.yaml
Increase the test coverage of the MySQL connector with a combination of unittests and integration tests.
> test: unittests for the MySQL connector

- ci/Dockerfile
- dozer-cli/src/cli/types.rs
- dozer-cli/src/main.rs
- dozer-tests/src/e2e_tests/checker/mod.rs
- dozer-tests/src/e2e_tests/runner/local.rs
> Change command to run_all to `dozer run`

- dozer-cli/src/errors.rs
- dozer-cli/src/live/state.rs
- dozer-cli/src/simple/build/contract/mod.rs
- dozer-cli/src/simple/build/contract/service.rs
- dozer-cli/src/simple/orchestrator.rs
- dozer-sql/src/pipeline/aggregation/factory.rs
- dozer-types/src/models/connection.rs
Now the graph looks like
Closes https://github.com/getdozer/dozer/issues/1922
> fix: Include connection type in `GenerateDot`. Fix `AggregationProcessorFactory::type_name`

- dozer-cli/src/simple/build/contract/service.rs
After this PR graph looks like
> fix: Don't show Table processor in dot graph

- dozer-cli/src/cli/types.rs
- dozer-cli/src/errors.rs
- dozer-cli/src/live/state.rs
- dozer-cli/src/main.rs
- dozer-cli/src/simple/build/contract/mod.rs
- dozer-cli/src/simple/build/contract/service.rs
- dozer-cli/src/simple/orchestrator.rs
- dozer-ingestion/tests/test_suite/connectors/dozer.rs
- dozer-tests/src/tests/e2e/mod.rs
> feat: Add --locked flag to build and run

- dozer-cli/src/errors.rs
- dozer-cli/src/pipeline/builder.rs
- dozer-sql/src/pipeline/builder.rs
- dozer-sql/src/pipeline/errors.rs
@aaryaattrey can you help add a test case for this?
> fix: Fix duplicate `INTO` check

- dozer-api/src/generator/protoc/generator/implementation.rs
- dozer-api/src/generator/protoc/generator/mod.rs
- dozer-cli/src/live/server.rs
- dozer-cli/src/live/state.rs
- dozer-cli/src/simple/build/contract/service.rs
- dozer-types/protos/contract.proto
Browsers cant natively support bi-directional streaming. Hence this behavior could be used to call typed service on the fly.
> feat: Implement get_protos

- dozer-cli/src/cli/cloud.rs
- dozer-cli/src/errors.rs
- dozer-cli/src/simple/cloud_orchestrator.rs
This allows us to do a locked build in cloud, if the lockfile is uploaded, to make sure the deployed version is actually what the user wants to deploy
> Upload lockfile when deploying

- .github/workflows/dozer.yaml
> Clippy all targets in lint workflow

- dozer-sql/src/pipeline/product/join/operator/table.rs
Turns out I lied about no behaviour change in #1971
> fix: Join table entries was not removed even if value is empty

- dozer-cli/src/pipeline/connector_source.rs
To save connectors from handling that case.
> chore: Handle empty `columns` in `ConnectorSouceFactory`

- dozer-types/protos/cloud.proto
related to this [PR](https://github.com/getdozer/dozer-cloud/pull/577)
> chore: clean up health check endpoint

- dozer-core/src/checkpoint/mod.rs
- dozer-core/src/errors.rs
- dozer-log/src/storage/queue.rs
Turns out s3 doesn't allow uploading a small part and then a big part. The "optimazation" doesn't work.
> fix: Fix checkpoint failure when using s3 storage

- dozer-cli/src/live/state.rs
This will ensure the home directory does not get deleted until the `stop` function is called.
> added temp_dir to LiveState

- dozer-api/src/cache_builder/mod.rs
- dozer-ingestion/src/connectors/dozer/connector.rs
- dozer-ingestion/src/errors.rs
- dozer-log-js/src/lib.rs
- dozer-log-python/src/lib.rs
- dozer-log/examples/reader.rs
- dozer-log/src/reader.rs
Depend on #2016 
Makes breaking change about the semantics of cache's metadata, but that metadata is soon to be changed so probably doesn't matter.
> feat: Make `DozerConnector` restartable

- dozer-types/protos/cloud.proto
related to [this](https://github.com/getdozer/dozer-cloud/pull/586)
> chore: add created_at, updated_at in deployment info

- Cargo.lock
- dozer-ingestion/Cargo.toml
- dozer-ingestion/src/connectors/snowflake/connection/client.rs
- dozer-ingestion/src/connectors/snowflake/connection/helpers.rs
- dozer-ingestion/src/connectors/snowflake/connection/mod.rs
- dozer-ingestion/src/connectors/snowflake/connection/pool.rs
- dozer-ingestion/src/connectors/snowflake/connector/snowflake.rs
- dozer-ingestion/src/connectors/snowflake/schema_helper.rs
- dozer-ingestion/src/connectors/snowflake/stream_consumer.rs
- dozer-ingestion/src/connectors/snowflake/test_utils.rs
- dozer-ingestion/src/connectors/snowflake/tests.rs
- dozer-ingestion/src/errors.rs
- dozer-ingestion/src/utils.rs
Implement network retry for the snowflake connector.
Part of #1916.
> fix: retry on network errors in the snowflake connector

- .github/workflows/coverage.yaml
- .github/workflows/release.yaml
- Cargo.lock
- Cross.toml
- ci/Dockerfile.aarch64-unknown-linux-gnu
- ci/Dockerfile.x86_64-unknown-linux-gnu
- ci/README.md
- dozer-cli/src/simple/executor.rs
- dozer-cli/src/simple/orchestrator.rs
- dozer-cli/src/utils.rs
- dozer-core/src/checkpoint/mod.rs
- dozer-core/src/executor/receiver_loop.rs
- dozer-recordstore/Cargo.toml
- dozer-recordstore/src/in_memory/mod.rs
- dozer-recordstore/src/in_memory/store.rs
- dozer-recordstore/src/lib.rs
- dozer-recordstore/src/rocksdb.rs
- dozer-sql/src/expression/tests/test_common.rs
- dozer-sql/src/product/join/operator/table.rs
- dozer-sql/src/product/set/record_map/mod.rs
- dozer-sql/src/table_operator/tests/operator_test.rs
- dozer-sql/src/utils/serialize.rs
- dozer-sql/src/window/tests/operator_test.rs
- dozer-storage/Cargo.toml
- dozer-storage/src/errors.rs
- dozer-storage/src/lib.rs
- dozer-storage/src/lmdb_database/lmdb_val.rs
- dozer-storage/src/rocksdb_map.rs
- dozer-types/src/models/app_config.rs
- json_schemas/dozer.json
> Revert "Revert "feat: Add option to use rocksdb record store""

- dozer-cli/src/cli/init.rs
- dozer-ingestion/src/connectors/snowflake/connector/snowflake.rs
- dozer-types/src/helper.rs
- dozer-types/src/ingestion_types.rs
- json_schemas/connections.json
- json_schemas/dozer.json
In case a user wants to change the default 5 seconds interval.
> feat: make polling interval configurable in snowflake config

- dozer-ingestion/src/connectors/snowflake/connection/client.rs
- dozer-ingestion/src/connectors/snowflake/stream_consumer.rs
Merge two queries, `EXISTS` and `CREATE`, into a single query `CREATE IF NOT EXISTS`.
> chore: remove unnecessary query in snowflake

- .github/workflows/release.yaml
- ci/Dockerfile
> Revert: enable onnxruntime

- dozer-sql/expression/src/onnx/udf.rs
> fix: onnx dimension problem

- Cargo.lock
- dozer-cli/Cargo.toml
- dozer-cli/src/cli/helper.rs
- dozer-cli/src/errors.rs
- dozer-cli/src/lib.rs
- dozer-cli/src/main.rs
- dozer-cli/src/pipeline/connector_source.rs
- dozer-cli/src/simple/orchestrator.rs
- Fix connectors command and replace ctrlc with tokio::signal
- Fix ctrl-c on `dozer connectors`
> Fix: `dozer connectors` command

- dozer-ingestion/src/connectors/postgres/xlog_mapper.rs
- dozer-ingestion/tests/test_suite/basic.rs
- dozer-ingestion/tests/test_suite/data.rs
> Fix postgres field reordering during CDC

- dozer-core/src/epoch/manager.rs
This check was removed because it prevented the log to be persisted. Now that we use different checks for checkpoint persisting and log persisting, this check should be added back.
> feat: Don't create checkpoint if source table is not restartable

- dozer-deno/src/runtime/mod.rs
- dozer-lambda/src/js/worker/mod.rs
Shouldn't have used one channel for all js function return values.
> fix: runtime might crash when using multiple lambdas

- Cargo.lock
- dozer-deno/Cargo.toml
- dozer-deno/src/lib.rs
- dozer-deno/src/runtime/js_runtime.rs
- dozer-deno/src/runtime/mod.rs
- dozer-deno/src/ts_module_loader/cache.rs
- dozer-deno/src/ts_module_loader/file_fetcher.rs
- dozer-deno/src/ts_module_loader/fs.rs
- dozer-deno/src/ts_module_loader/http_util.rs
- dozer-deno/src/ts_module_loader/mod.rs
- dozer-deno/src/ts_module_loader/text_encoding.rs
- dozer-ingestion/javascript/src/js_extension/mod.rs
Adapted `FileFetcher` from `deno_cli`.
> feat: Support importing modules in js apps

- dozer-cli/src/live/state.rs
- dozer-cli/src/main.rs
- dozer-cli/src/simple/orchestrator.rs
- dozer-ingestion/tests/test_suite/connectors/dozer.rs
- dozer-sql/src/pipeline_builder/from_builder.rs
- dozer-sql/src/pipeline_builder/join_builder.rs
- dozer-tests/src/tests/e2e/mod.rs
Previously fatal error in pipeline was not reported until API server stops.
> fix: Properly report error happened in pipeline

- dozer-cli/src/pipeline/dummy_sink.rs
1. `psql -h localhost -U chubei bench_2 -c "drop table if exists latency_test; create table latency_test(inserted_at TIMESTAMPTZ);"`
2. Run dozer with following config:
```yaml
app_name: dozer-pg-sample
version: 1
connections:
- name: dozer_pg_db
config: !Postgres
user: chubei
password: postgres
host: localhost
port: 5432
database: bench_2
endpoints:
- table_name: latency_test
kind: !Dummy
```
3. `psql -h localhost -U chubei bench_2 -c "insert into latency_test values (now());"`
Dozer should print something like `INFO Latency: 2ms`
> chore: Add latency measuring code in dummy sink

- dozer-cli/src/simple/orchestrator.rs
- dozer-ingestion/mysql/src/binlog.rs
- dozer-ingestion/mysql/src/connector.rs
- dozer-ingestion/mysql/src/lib.rs
- dozer-ingestion/mysql/src/state.rs
> feat: Continue mysql ingestion

- dozer-core/src/executor/mod.rs
> fix: `dozer-core` now propagates recoverable errors instead of panicking

- Cargo.lock
- dozer-cli/src/pipeline/builder.rs
- dozer-ingestion/Cargo.toml
- dozer-ingestion/connector/src/ingestor.rs
- dozer-ingestion/oracle/Cargo.toml
- dozer-ingestion/oracle/src/connector/join.rs
- dozer-ingestion/oracle/src/connector/listing.rs
- dozer-ingestion/oracle/src/connector/mapping.rs
- dozer-ingestion/oracle/src/connector/mod.rs
- dozer-ingestion/oracle/src/lib.rs
- dozer-ingestion/src/lib.rs
- dozer-tests/src/e2e_tests/runner/running_env.rs
- dozer-types/src/models/connection.rs
- dozer-types/src/models/ingestion_types.rs
- json_schemas/dozer.json
Oracle database setup: https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md#running-oracle-database-enterprise-and-standard-edition-2-in-a-container
> feat: Oracle connector snapshotting

- dozer-cli/src/cli/helper.rs
- dozer-cli/src/cli/types.rs
- dozer-cli/src/live/state.rs
- dozer-cli/src/main.rs
- dozer-cli/src/pipeline/builder.rs
- dozer-cli/src/pipeline/tests/builder.rs
- dozer-cli/src/simple/build/contract/mod.rs
- dozer-cli/src/simple/executor.rs
- dozer-cli/src/simple/helper.rs
- dozer-cli/src/simple/orchestrator.rs
- dozer-ingestion/postgres/src/tests/dozer-config.yaml
- dozer-ingestion/snowflake/src/tests/dozer-config.yaml
- dozer-ingestion/src/errors.rs
- dozer-ingestion/src/lib.rs
- dozer-ingestion/tests/test_suite/connectors/dozer.rs
- dozer-sink-aerospike/aerospike-client-sys/aerospike_client.h
- dozer-sink-aerospike/src/lib.rs
- dozer-tests/src/e2e_tests/checker/client.rs
- dozer-tests/src/e2e_tests/runner/running_env.rs
- dozer-types/src/models/config.rs
- dozer-types/src/models/connection.rs
- dozer-types/src/models/endpoint.rs
- json_schemas/dozer.json
- Add support for json fields to aerospike sink
- Aerospike basic normalization
- Allow re-use of connection config
> aerospike denorm

- dozer-ingestion/oracle/src/connector/mod.rs
- dozer-ingestion/oracle/src/connector/replicate/listing.rs
- dozer-sink-oracle/src/lib.rs
- Retry when oracle skips sequence numbers
- Make oracle sink string columns VARCHAR2
> oracle source fix

- dozer-cli/src/cli/types.rs
- dozer-cli/src/main.rs
Rebased version of #2379 @MG190202
> Cli changes

- dozer-cli/src/pipeline/builder.rs
- dozer-core/src/app.rs
- dozer-core/src/tests/app.rs
- dozer-sql/src/aggregation/factory.rs
- dozer-sql/src/aggregation/tests/aggregation_test_planner.rs
- dozer-sql/src/aggregation/tests/aggregation_tests_utils.rs
- dozer-sql/src/builder/common.rs
- dozer-sql/src/builder/from.rs
- dozer-sql/src/builder/join.rs
- dozer-sql/src/builder/mod.rs
- dozer-sql/src/builder/table_operator.rs
- dozer-sql/src/planner/projection.rs
- dozer-sql/src/planner/tests/projection_tests.rs
- dozer-sql/src/planner/tests/schema_tests.rs
- dozer-sql/src/product/table/factory.rs
- dozer-sql/src/tests/builder_test.rs
- dozer-tests/src/sql_tests/helper/pipeline.rs
90 more lines removed. Hopefully this makes the code more readable.
> chore: Remove clones and duplicated code in `dozer_sql::builder`
