Cargo.lock, dozer-types/Cargo.toml
This reverts commit 118d0fa5e4b7d28348fc06a7e38cacd6fda683be.
=> Revert "Bump chrono from 0.4.22 to 0.4.23 (#697)"

dozer-core/src/dag/dag_metadata.rs, dozer-core/src/dag/epoch.rs, dozer-core/src/dag/errors.rs, dozer-core/src/dag/executor.rs, dozer-core/src/dag/executor/receiver_loop.rs, dozer-core/src/dag/forwarder.rs, dozer-core/src/dag/tests/checkpoint_ns.rs, dozer-core/src/dag/tests/dag_recordreader.rs, dozer-core/src/dag/tests/dag_recordreader_update.rs, dozer-orchestrator/src/pipeline/sinks.rs
`None` is not persisted.
Closes #773
=> refactor: Only persist checkpoint states of relevant sources.

dozer-core/src/dag/dag_impl.rs, dozer-core/src/dag/dag_schemas.rs, dozer-core/src/dag/errors.rs, dozer-core/src/dag/executor.rs, dozer-core/src/dag/executor_utils.rs, dozer-core/src/dag/forwarder.rs, dozer-core/src/dag/node.rs, dozer-core/src/dag/tests/app.rs, dozer-core/src/dag/tests/dag_schemas.rs, dozer-orchestrator/src/simple/orchestrator.rs, dozer-tests/src/sql_tests/pipeline.rs
This PR merges `Dag` and `DagSchema` to a single struct `DagSchema`, and keeps the schema information on the edges, for convenient future use.
A side effect is that, now if an output port is not used (not connected to any input port), we won't try to get its schema.
I'm not sure if it's the behaviour we want? @snork-alt
=> refactor: Don't try to get schema of unconnected ports

dozer-core/src/dag/epoch.rs, dozer-core/src/dag/forwarder.rs
=> feat: All nodes use the same instant for commit timeout

dozer-core/src/dag_impl.rs, dozer-core/src/dag_metadata.rs, dozer-core/src/dag_schemas.rs, dozer-core/src/epoch.rs, dozer-core/src/executor.rs, dozer-core/src/executor/execution_dag.rs, dozer-core/src/executor/processor_node.rs, dozer-core/src/executor/sink_node.rs, dozer-core/src/executor/source_node.rs, dozer-core/src/executor_utils.rs, dozer-core/src/forwarder.rs, dozer-core/src/lib.rs, dozer-core/src/node.rs, dozer-core/src/record_store.rs, dozer-core/src/tests.rs, dozer-core/src/tests/app.rs, dozer-core/src/tests/dag_schemas.rs, dozer-core/src/tests/processors.rs, dozer-core/src/tests/record_store.rs, dozer-core/src/tests/sinks.rs, dozer-core/src/tests/sources.rs, dozer-orchestrator/src/simple/orchestrator.rs, dozer-sql/src/pipeline/aggregation/tests/aggregation_sum_tests.rs, dozer-tests/src/sql_tests/pipeline.rs
This PR splits the execution dag's construction phase and execution phase.
The construction phase is self-contained in `ExecutionDag::new` and can be reused across different execution stages.
Utilizing the DAG structure of `ExecutionDag`, we're able to get rid of the overwhelming type `Arc<RwLock<HashMap<NodeHandle, HashMap<PortHandle, Box<dyn RecordReader>>>>>`.
We also added a extra validation step in `DagSchemas::new`, which checks if the dag is properly connected so that data can flow from source to sink.
=> refactor: Split execution dag construction and execution

dozer-api/src/api_helper.rs, dozer-api/src/grpc/common/service.rs, dozer-api/src/grpc/shared_impl/mod.rs, dozer-api/src/grpc/typed/service.rs, dozer-api/src/grpc/typed/tests/service.rs, dozer-api/src/lib.rs, dozer-api/src/rest/api_generator.rs, dozer-api/src/rest/tests/auth.rs, dozer-api/src/rest/tests/routes.rs, dozer-cache/src/reader.rs, dozer-orchestrator/src/simple/orchestrator.rs
This is part of the typed service refactoring.
=> chore: Don't hold `AccessFilter` in `CacheReader`. Don't hold `CacheReader` or `ApiEndpoint` in `ApiHelper`

dozer-api/src/grpc/typed/service.rs, dozer-api/src/rest/tests/auth.rs
=> fix: `TypedService` didn't filter events based on endpoint

dozer-api/src/api_helper.rs, dozer-cache/src/cache/lmdb/cache/mod.rs, dozer-cache/src/cache/lmdb/tests/basic.rs, dozer-cache/src/cache/lmdb/tests/read_write.rs, dozer-cache/src/cache/mod.rs, dozer-cache/src/reader.rs, dozer-orchestrator/src/pipeline/sinks.rs, dozer-types/src/helper.rs, dozer-types/src/lib.rs
Moved `record_to_map` out of `dozer_types` because now it uses `RecrodWithId` from `dozer-cache`.
Query:
Get using PK:
=> feat: Return record id and version in REST API

dozer-ingestion/src/connectors/object_store/table_reader.rs
- Refactored how the `fields` vector is built to avoid reallocations
- Extracted some duplicated code into functions to DRY
- Replaced `map_or_else()` for `ok_or()` to reduce verbosity
- Reduced verbosity of errors
=> Reduce allocations & clones. Minor improved ergonomics

dozer-api/src/generator/protoc/generator/mod.rs
When trying to run the code base it compiles but it fails to run as the `types.proto` file is not copied to the `.dozer/api/generated` folder
=> Add missing types.proto reference

dozer-api/src/grpc/client_server.rs, dozer-api/src/grpc/health/service.rs, dozer-api/src/grpc/health/tests/mod.rs, dozer-tests/src/e2e_tests/cases/flags_dynamic_false/dozer-config.yaml, dozer-tests/src/e2e_tests/cases/flags_dynamic_false/expectations.json
I think this implementation still conforms to https://grpc.github.io/grpc/core/md_doc_health-checking.html while not having the problem returning `NotServing` for empty string when `dynamic` is `false`.
=> fix: Health check should not return `NotServing` when `dynamic` is `false`

dozer-api/protos/films.proto, dozer-api/protos/types.proto, dozer-api/src/generator/protoc/generator/implementation.rs, dozer-api/src/generator/protoc/generator/mod.rs, dozer-api/src/generator/protoc/generator/template/proto.tmpl, dozer-api/src/grpc/shared_impl/filter/tests.rs, dozer-api/src/grpc/typed/helper.rs, dozer-api/src/grpc/typed/tests/fake_internal_pipeline_server.rs, dozer-api/src/grpc/types_helper.rs, dozer-cache/src/cache/lmdb/cache/mod.rs, dozer-cache/src/cache/mod.rs, dozer-orchestrator/src/pipeline/sinks.rs
Currently only `INSERT` operation gets `id`.
typed:
common:
=> feat: Include id in grpc event stream

Cargo.lock, dozer-sql/Cargo.toml, dozer-sql/src/pipeline/errors.rs, dozer-sql/src/pipeline/expression.rs, dozer-sql/src/pipeline/expression/builder.rs, dozer-sql/src/pipeline/expression/execution.rs, dozer-sql/src/pipeline/expression/python_udf.rs, dozer-tests/Cargo.toml, dozer-tests/src/tests/sql/mod.rs, dozer-types/Cargo.toml, dozer-types/src/lib.rs, dozer-types/src/types/field.rs, dozer-types/src/types/tests.rs
Running into issues running because of new dependencies.
```
bs"
= note: ld: warning: directory not found for option '-L/opt/homebrew/opt/odbc/lib'
ld: warning: directory not found for option '-L/opt/homebrew/opt/odbc/lib'
Undefined symbols for architecture arm64:
"_ERR_get_error_all", referenced from:
openssl::error::Error::get::h10687d4ca56e2d56 in libopenssl-2efd15f3d78a2746.rlib(openssl-2efd15f3d78a2746.openssl.d451f57b-cgu.5.rcgu.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Moving python under a feature flag `python`. 
@xudong963 Can you verify ?
=> chore: introduce python feature flag

dozer-ingestion/src/connectors/kafka/tests.rs, dozer-ingestion/src/connectors/mod.rs, dozer-ingestion/src/connectors/postgres/tests/e2e.rs, dozer-ingestion/src/connectors/snowflake/test_utils.rs, dozer-ingestion/src/errors.rs, dozer-tests/src/e2e_tests/runner/running_env.rs, dozer-types/src/models/connection.rs
Fixes #954 
Now the error message is:
```text
2023-02-21T08:37:19.596601Z ERROR [eth_logs] X Connection validation error: Missing `config` for connector eth_logs    
2023-02-21T08:37:19.597035Z ERROR Source validation failed   
```
=> fix: Don't create default connector config

dozer-api/src/api_helper.rs, dozer-api/src/errors.rs, dozer-api/src/generator/oapi/generator.rs, dozer-api/src/generator/protoc/generator/implementation.rs, dozer-api/src/generator/protoc/generator/mod.rs, dozer-api/src/generator/protoc/tests.rs, dozer-api/src/grpc/common/service.rs, dozer-api/src/grpc/shared_impl/mod.rs, dozer-api/src/rest/api_generator.rs, dozer-api/src/rest/tests/routes.rs, dozer-api/src/test_utils.rs, dozer-cache/benches/cache.rs, dozer-cache/src/cache/lmdb/cache/mod.rs, dozer-cache/src/cache/lmdb/cache/query/handler.rs, dozer-cache/src/cache/lmdb/cache/query/tests.rs, dozer-cache/src/cache/lmdb/cache/schema_database.rs, dozer-cache/src/cache/lmdb/cache_manager.rs, dozer-cache/src/cache/lmdb/indexer.rs, dozer-cache/src/cache/lmdb/tests/basic.rs, dozer-cache/src/cache/lmdb/tests/read_write.rs, dozer-cache/src/cache/lmdb/tests/utils.rs, dozer-cache/src/cache/mod.rs, dozer-cache/src/errors.rs, dozer-cache/src/reader.rs, dozer-orchestrator/src/pipeline/builder.rs, dozer-orchestrator/src/pipeline/sinks.rs, dozer-orchestrator/src/test_utils.rs, dozer-tests/src/cache_tests/film/load_database.rs, dozer-tests/src/cache_tests/skip_and_limit.rs, dozer-tests/src/tests/cache.rs
`RwCache::insert_schema` is removed, and `CacheManager::create_cache` not takes a `schemas` parameter.
All schema writes are performed at cache creation. Implemented in `LmdbRwCache::create`.
Schema lookup is changed from database read from hash map lookup. Implemented in `dozer-cache/src/cache/lmdb/cache/schema_database.rs`.
`RoCache::get_schema` and `RoCache::query` now returns `&Schema` to avoid cloning or repetitive lookup.
Remove `ApiHelper` and use free functions instead. Functions only used in REST are moved to `dozer-api/src/rest/api_generator.rs`.
`MultiIndexFetch` is moved from `CacheError` to `ApiError`.
`OpenApiGenerator`, `ProtoGeneratorImpl` and `LmdbQueryHandler` now own references instead of values.
=> perf: Remove `RwCache::insert_schema` so we don't read the db on every insert

.github/workflows/coverage.yaml
This saves CI compilation time.
=> chore: Remove `cargo test connector_e2e_` because there's no test.

dozer-ingestion/src/connectors/snowflake/connector.rs
Fixes build error 
```
error[E0432]: unresolved import `crate::connectors::snowflake::schema_helper`
--> dozer-ingestion/src/connectors/snowflake/connector.rs:17:35
|
17 | use crate::connectors::snowflake::schema_helper::SchemaHelper;
|                                   ^^^^^^^^^^^^^ could not find `schema_helper` in `snowflake`
```
=> fix: Fix snowflake schema helper import

.github/workflows/pulls.yaml
Example PR: #1025
I have to put title in the message if body is null because Github Action doesn't allow string literal in the expression
=> chore: Don't fail discord notification when PR has no comment

dozer-types/build.rs
=> fix: Remove non-existent proto include, which made cargo always rerun

dozer-cache/src/cache/lmdb/indexer.rs
Spotted this in the flamegraph.
Tested using data and config of `taxi-objectstore` in https://github.com/getdozer/dozer-samples-internal/commit/e4b719153a9d82f5fba55bb9637d44cd946f6304. Run following command:
```bash
rm -r .dozer; time ~/dozer/target/release/dozer
```
When `trips_cache` count reaches 200,000, press Ctrl + C and wait for dozer to quit.
With code in https://github.com/getdozer/dozer/commit/0c549a28f39c3f440b4768412fff7c616b7eaa5e:
`~/dozer/target/release/dozer  28.25s user 23.84s system 101% cpu 51.526 total`
With code in https://github.com/chubei/dozer/commit/ac46db09aca5b0751b07aaf69bb28acda872ee48:
`~/dozer/target/release/dozer  13.62s user 10.19s system 115% cpu 20.578 total`
Saves 60%.
=> perf: Remove usage of nested lmdb transaction

dozer-orchestrator/src/pipeline/connector_source.rs, dozer-orchestrator/src/pipeline/sinks.rs
```text
stocks_meta: ▹▸▹▹▹ 8000 : 15,717.4372/s
stocks: ▸▹▹▹▹ 19000 : 102,344.652/s
stocks_meta: ▹▸▹▹▹ 8000 : 15,717.4372/s
stocks: ▹▸▹▹▹ 20000 : 103,526.3387/s
stocks_meta: ▹▸▹▹▹ 8000 : 15,717.4372/s
stocks: ▹▸▹▹▹ 20000 : 103,526.3387/s
▸▹▹▹▹ stocks 20049 : 19,054.2494/s
▸▹▹▹▹ stocks_meta 8050 : 1,269.6193/s                                   
```
```text
▹▹▹▸▹ stocks: 16000: 26,675.5882/s
▹▸▹▹▹ stocks_meta: 8000: 14,558.2636/s
▹▸▹▹▹ stocks: 20000: 103,293.2523/s
▹▸▹▹▹ stocks_meta: 8000: 14,558.2636/s
▹▸▹▹▹ stocks: 20000: 103,293.2523/s
▹▸▹▹▹ stocks_meta: 8000: 14,558.2636/s
▹▸▹▹▹ stocks: 20049: 1,214.6517/s
▹▸▹▹▹ stocks_meta: 8050: 919.5672/s      
```
=> fix: Use same progress bar style (expect for color) for source and sink

dozer-admin/Cargo.toml, dozer-api/Cargo.toml, dozer-cache/Cargo.toml, dozer-core/Cargo.toml, dozer-ingestion/Cargo.toml, dozer-orchestrator/Cargo.toml, dozer-sql/Cargo.toml, dozer-storage/Cargo.toml, dozer-tests/Cargo.toml, dozer-tracing/Cargo.toml, dozer-types/Cargo.toml
Deb package generation requires authors defined in packages
=> chore: Add authors to packages

ci/download-latest.sh
fix: updated download_binary
check working os
=> fix: updated download_binary

.github/workflows/coverage.yaml, .github/workflows/dozer.yaml, .github/workflows/release.yaml
=> chore: Use 16 cores runner for coverage and release, 4 cores runner for lint

dozer-core/Cargo.toml
The unused dependency of unixstring was causing build failure of native windows binary.
=> remove unused dependency

dozer-sql/src/pipeline/aggregation/avg.rs, dozer-sql/src/pipeline/aggregation/count.rs, dozer-sql/src/pipeline/aggregation/max.rs, dozer-sql/src/pipeline/aggregation/min.rs, dozer-sql/src/pipeline/aggregation/sum.rs, dozer-sql/src/pipeline/expression/builder.rs, dozer-sql/src/pipeline/expression/datetime.rs, dozer-sql/src/pipeline/expression/scalar/tests/datetime.rs
https://www.postgresqltutorial.com/postgresql-date-functions/postgresql-extract/
- Implement `extract(day from date)` syntax which is natively supported in SQL. 
- This can replace day_of_week function
Sample queries
```
select extract(timezone from last_update) from actor;
select extract(year from last_update) from actor;
select extract(hour from last_update) from actor;
select extract(month from last_update) from actor;
```
```
DateTimeField::Dow => ts.weekday().num_days_from_monday().to_i64(),
DateTimeField::Day => ts.day().to_i64(),
DateTimeField::Month => ts.month().to_i64(),
DateTimeField::Year => ts.year().to_i64(),
DateTimeField::Hour => ts.hour().to_i64(),
DateTimeField::Minute => ts.minute().to_i64(),
DateTimeField::Second => ts.second().to_i64(),
DateTimeField::Millisecond | …
```
=> feat: implement date extract

dozer-admin/src/services/connection_service.rs, dozer-ingestion/benches/helper.rs, dozer-ingestion/src/connectors/delta_lake/connector.rs, dozer-ingestion/src/connectors/delta_lake/schema_helper.rs, dozer-ingestion/src/connectors/delta_lake/test/deltalake_test.rs, dozer-ingestion/src/connectors/ethereum/log/connector.rs, dozer-ingestion/src/connectors/ethereum/trace/connector.rs, dozer-ingestion/src/connectors/grpc/connector.rs, dozer-ingestion/src/connectors/grpc/tests.rs, dozer-ingestion/src/connectors/kafka/connector.rs, dozer-ingestion/src/connectors/kafka/debezium/no_schema_registry.rs, dozer-ingestion/src/connectors/kafka/debezium/schema_registry.rs, dozer-ingestion/src/connectors/mod.rs, dozer-ingestion/src/connectors/object_store/connector.rs, dozer-ingestion/src/connectors/object_store/schema_mapper.rs, dozer-ingestion/src/connectors/postgres/connector.rs, dozer-ingestion/src/connectors/postgres/test_utils.rs, dozer-ingestion/src/connectors/postgres/xlog_mapper.rs, dozer-ingestion/src/connectors/snowflake/connection/client.rs, dozer-ingestion/src/connectors/snowflake/connector.rs, dozer-ingestion/src/connectors/snowflake/schema_helper.rs, dozer-ingestion/src/connectors/snowflake/tests.rs, dozer-orchestrator/src/pipeline/connector_source.rs, dozer-orchestrator/src/pipeline/validate.rs, dozer-orchestrator/src/simple/executor.rs
Postgres connector were initiated without tables config, so during publication slot creation it was always creating slot for all tables. This was causing issue in replication, because we were receiving data from tables, which were not used in sources.
In this changeset, I have added second argument `tables` to `get_connector` method and use that value in postgres connector initialization.
=> fix: Fix publication slot creation

dozer-cache/src/cache/lmdb/cache/main_environment/operation_log/mod.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/mod.rs, dozer-cache/src/cache/lmdb/indexing.rs
This problem happens once in a while, but seems to be recoverable, so we just ignore the error when an operation cannot be found and retry later. Example log:
```
2023-03-16T15:03:02.358474Z DEBUG Operation 27999 not found    
2023-03-16T15:03:02.358482Z DEBUG Operation 28002 not found    
2023-03-16T15:03:02.358480Z DEBUG Operation 28530 not found    
2023-03-16T15:03:02.358480Z DEBUG Operation 28473 not found    
2023-03-16T15:03:02.463046Z DEBUG Operation 33893 not found    
2023-03-16T15:03:02.463046Z DEBUG Operation 33246 not found    
2023-03-16T15:03:02.463092Z DEBUG Operation 33303 not found    
2023-03-16T15:03:02.463046Z DEBUG Operation 33891 not found    
2023-03-16T15:03:02.567920Z DEBUG Operation 38659 not found    
2023-03-16T15:03:02.567925Z DEBUG Operation 38589 not found …
```
=> fix: Don't panic if operation cannot be read from indexing thread.

.gitignore, dozer-tests/README.md, dozer-tests/src/e2e_tests/case.rs, dozer-tests/src/e2e_tests/cases/dozer-samples-connectors-local-storage/dozer-config.yaml, dozer-tests/src/e2e_tests/cases/dozer-samples-connectors-local-storage/expectations.json, dozer-tests/src/e2e_tests/connections/ny_taxi/init.sh, dozer-tests/src/e2e_tests/connections/ny_taxi/service.yaml, dozer-tests/src/e2e_tests/docker_compose.rs, dozer-tests/src/e2e_tests/runner/running_env.rs
This PR adds the necessary mechanism for setting up a local storage connector in e2e tests, and adds a new e2e test according to https://github.com/getdozer/dozer-samples/tree/main/connectors/local-storage.
It also implements the local storage connection `ny_taxi` used by the test.
=> test: Add ny taxi sample to e2e tests

Cargo.lock, dozer-ingestion/Cargo.toml, dozer-ingestion/src/connectors/mod.rs, dozer-ingestion/tests/test_connectors.rs, dozer-ingestion/tests/test_suite/basic.rs, dozer-ingestion/tests/test_suite/connectors/arrow.rs, dozer-ingestion/tests/test_suite/connectors/mod.rs, dozer-ingestion/tests/test_suite/connectors/object_store/local_storage.rs, dozer-ingestion/tests/test_suite/connectors/object_store/mod.rs, dozer-ingestion/tests/test_suite/data.rs, dozer-ingestion/tests/test_suite/mod.rs, dozer-types/src/types/field.rs
This PR adds the `basic` test suite for connectors and the test implementation of the `LocalStorage`.
The test data is only one `Insert` with one field now. It's yet to be extended.
=> test: `LocalStorage` basic test

dozer-ingestion/src/connectors/grpc/connector.rs, dozer-ingestion/tests/test_connectors.rs, dozer-ingestion/tests/test_suite/basic.rs, dozer-ingestion/tests/test_suite/connectors/arrow.rs, dozer-ingestion/tests/test_suite/connectors/object_store/local_storage.rs, dozer-ingestion/tests/test_suite/data.rs, dozer-ingestion/tests/test_suite/mod.rs
This PR adds another connector test trait `DataReadyConnectorTest`, which requires the connector to setup data by itself, instead of using test suite generated data.
This serves the purpose of data type test. There's only one (or zero) way to map a dozer type to an external type, but many external types may be mapped to the same dozer type. `DataReadyConnectorTest` should generate such a database that every possible external data type is covered.
`LocalStorage` implements this trait and exposes two bugs. We've temporarily disabled checking the buggy data types so this PR can be merged.
=> test: Add `DataReadyConnectorTest` and implement `LocalStorage`

Cargo.lock, dozer-storage/Cargo.toml, dozer-storage/src/errors.rs, dozer-storage/src/lmdb_storage.rs
Lmdb map size must be a multiple of system page size, but it didn't check that.
Wrong map size may result in lmdb crash later, so we check before creating the environment.
=> chore: Check map size before creating lmdb environment

dozer-api/src/grpc/common/tests/mod.rs, dozer-cache/src/cache/lmdb/cache/mod.rs, dozer-cache/src/cache/lmdb/cache/query/tests.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/indexer.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/mod.rs, dozer-cache/src/cache/lmdb/cache_manager.rs, dozer-cache/src/cache/lmdb/indexing.rs, dozer-cache/src/cache/lmdb/tests/basic.rs, dozer-cache/src/cache/lmdb/tests/read_write.rs, dozer-cache/src/cache/lmdb/tests/utils.rs, dozer-storage/src/tests/lmdb_sys.rs
The indexing threads used to be looping even if there's nothing to index.
This PR fixes that. Now the indexing threads will go idle if secondary indexes are up to date. The main database commit will wake up the indexing threads.
Part of #1285
=> perf: Put indexing thread pool to idle if indexes are up to date

dozer-orchestrator/src/main.rs, dozer-orchestrator/src/simple/orchestrator.rs
Fixes #1285 
Two different CPU usage problem.
In `dozer`, there's an unnecessary `while` loop before joining the pipeline thread. Joining is already blocking.
In `dozer api run`, there's a `while` hack because api server doesn't respect `running` flag. We put a `sleep` in the loop.
=> chore: Remove unused spin loop in `run_all`. Sleep in spin loop of api thread.

Cargo.lock, dozer-orchestrator/Cargo.toml, dozer-orchestrator/src/cli/helper.rs, dozer-orchestrator/src/main.rs
Use experience is better this way. They can use arbitrary `max_cache_map_size` instead of calculating multiple of `4096` or `16384`.
=> chore: Round `cache_max_map_size` to multiple of page size

dozer-api/src/errors.rs, dozer-api/src/rest/api_generator.rs, dozer-cache/benches/cache.rs
Support for env variables in the bench script so it could be tuned without changing code.
=> chore: include env variables in cache benchmark

dozer-cache/src/cache/lmdb/cache/main_environment/operation_log/mod.rs, dozer-storage/src/lmdb_database/lmdb_val.rs, dozer-storage/src/lmdb_map.rs, dozer-types/src/borrow/mod.rs
Closes #1215 
With config file:
```yaml
connections:    
- config : !LocalStorage
details:
path: data
tables:
- !Table
name: trips
prefix: /trips
file_type: parquet
extension: .parquet
name: ny_taxi
endpoints:
- name: trips
path: /trips
table_name: trips
cache_max_map_size: 10000000000
```
and data from `dozer-samples-connectors-local-storage` e2e test.
Comment https://github.com/getdozer/dozer/blob/main/dozer-api/src/cache_builder/log_reader.rs#L73.
```bash
dozer migrate
dozer app run
```
`time cargo run -- release dozer -- api run`
Hit Ctrl + C when counter reaches 3_000_000.
```text
cargo run --release -- api run  168.85s user 13.52s system 264% cpu 1:09.03 total
```
```text
cargo run --release -- api run  64.95s user 0.91s system 464% cpu 14.188 total
```
5x speed up.
=> perf: Use `MDB_APPEND` when possible

dozer-ingestion/src/connectors/object_store/table_reader.rs, dozer-ingestion/src/connectors/object_store/tests/local_storage_tests.rs, dozer-ingestion/src/errors.rs
=> feature: Read object store files in parallel

dozer-sql/src/pipeline/aggregation/avg.rs, dozer-sql/src/pipeline/aggregation/count.rs, dozer-sql/src/pipeline/aggregation/max.rs, dozer-sql/src/pipeline/aggregation/min.rs, dozer-sql/src/pipeline/aggregation/sum.rs, dozer-sql/src/pipeline/aggregation/tests/aggregation_avg_tests.rs, dozer-sql/src/pipeline/aggregation/tests/aggregation_count_tests.rs, dozer-sql/src/pipeline/aggregation/tests/aggregation_max_tests.rs, dozer-sql/src/pipeline/aggregation/tests/aggregation_min_tests.rs, dozer-sql/src/pipeline/aggregation/tests/aggregation_sum_tests.rs, dozer-sql/src/pipeline/aggregation/tests/aggregation_tests_utils.rs, dozer-sql/src/pipeline/expression/builder.rs, dozer-sql/src/pipeline/expression/datetime.rs, dozer-sql/src/pipeline/expression/execution.rs, dozer-sql/src/pipeline/expression/tests/datetime.rs, dozer-types/src/types/field.rs, dozer-types/src/types/mod.rs, dozer-types/src/types/tests.rs
Aggregation Support
SQL Representation
Currently only supported TimeUnits are:
* `SECOND` with up to u64  due to https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/std/time/struct.Duration.html#method.from_secs
* `MILLISECOND` or `MILLISECONDS` with up to u64 due to https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/std/time/struct.Duration.html#method.from_millis
* `MICROSECOND` or `MICROSECONDS` with up to u64 due to https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/std/time/struct.Duration.html#method.from_micros
* `NANOSECOND` or `NANOSECONDS` with up to u64 due to https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/std/time/struct.Duration.html#method.from_nanos
=> feat: `Duration` for sql representation + aggregation support

.github/workflows/e2e.yaml
=> chore: Don't cancel e2e runs on `main`

dozer-api/src/cache_builder/mod.rs, dozer-api/src/lib.rs, dozer-api/src/test_utils.rs, dozer-cache/benches/cache.rs, dozer-cache/src/cache/lmdb/cache/main_environment/conflict_resolution_tests.rs, dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs, dozer-cache/src/cache/lmdb/cache/mod.rs, dozer-cache/src/cache/lmdb/cache_manager.rs, dozer-cache/src/cache/lmdb/tests/read_write.rs, dozer-cache/src/cache/lmdb/tests/utils.rs, dozer-cache/src/cache/mod.rs, dozer-tests/src/cache_tests/film/load_database.rs, dozer-types/src/models/api_endpoint.rs
This is a simple refactor for adding more options to `CacheWriteOptions` in the following PR.
=> chore: Use `CacheWriteOptions` instead of `ConflictResolution`

dozer-admin/src/tests/applications.rs, dozer-core/src/errors.rs, dozer-orchestrator/src/simple/orchestrator.rs, dozer-orchestrator/src/utils.rs, dozer-tests/src/tests/e2e/basic.rs, dozer-tests/src/tests/e2e/basic_sql.rs, dozer-tests/src/tests/e2e/mod.rs, dozer-types/src/models/app_config.rs
There were two bugs:
1. The generated `TempDir` was set to `home_dir` but `TempDir` is dropped earlier than dozer finishes, so dozer creates the directory again and not removed.
2. `cache_dir` was not set using `TempDir` and results in dozer writing to `./.dozer/cache`.
=> fix: e2e tests write to directories that are not removed

dozer-cache/src/cache/lmdb/cache/main_environment/conflict_resolution_tests.rs, dozer-sql/src/pipeline/expression/comparison.rs, dozer-sql/src/pipeline/expression/execution.rs, dozer-sql/src/pipeline/expression/tests/comparison.rs
=> fix: type validation

dozer-api/examples/reader.rs, dozer-api/src/cache_builder/log_reader.rs, dozer-api/src/cache_builder/mod.rs, dozer-api/src/grpc/typed/tests/service.rs, dozer-api/src/lib.rs, dozer-api/src/rest/tests/auth.rs, dozer-api/src/rest/tests/routes.rs, dozer-api/src/test_utils.rs, dozer-orchestrator/src/simple/orchestrator.rs
Otherwise one of the tokio worker threads is blocked and can't be used for other tasks.
Also, tokio runtime will block forever when shutdown because we never yield.
=> fix: Use `tokio::time::sleep` instead of `std::thread::sleep`

dozer-cache/src/reader.rs
So users don't have to write `{ "fields": [] }` when generating a token.
=> chore: Make `AccessFilter::fields` optional

Cargo.lock, dozer-admin/src/services/application_service.rs, dozer-ingestion/Cargo.toml, dozer-orchestrator/Cargo.toml, dozer-orchestrator/src/cli/helper.rs, dozer-orchestrator/src/cli/init.rs, dozer-orchestrator/src/cli/mod.rs, dozer-orchestrator/src/errors.rs, dozer-orchestrator/src/simple/orchestrator.rs, dozer-tests/src/e2e_tests/case.rs, dozer-tests/src/tests/e2e/mod.rs
Part of #1408 
Tested with
```bash
cargo run -- -c https://raw.githubusercontent.com/getdozer/dozer-samples/main/connectors/local-storage/dozer-config.yaml
```
Also fixes #1345.
=> feat: Support loading dozer config from an url.

Cargo.lock, dozer-cache/src/cache/lmdb/cache/secondary_environment/indexer.rs, dozer-ingestion/Cargo.toml, dozer-ingestion/src/connectors/postgres/helper.rs, dozer-ingestion/tests/test_suite/connectors/sql.rs
(cherry picked from commit 82551d116a68b26a7b9a1088971fd220745b4eab)
=> fix: uuid postgres type support

dozer-api/src/cache_builder/mod.rs, dozer-api/src/lib.rs, dozer-api/src/test_utils.rs, dozer-cache/src/cache/plan/planner.rs, dozer-cache/src/errors.rs, dozer-types/src/lib.rs, dozer-types/src/models/api_endpoint.rs, dozer-types/src/tests.rs, dozer-types/src/tests/secondary_index_yaml_deserialize.rs
This PR adds to the configuration file the option of skip default secondary indexes and create new indexes.
The configuration format is not as nice as we wanted because protobuf doesn't support `repeated oneof` or `repeated` within `oneof`. On that note, I think it's time to consider decoupling our configuration format and protobuf.
Closes #1445.
Tested with data in https://github.com/getdozer/dozer-samples/tree/main/sql/join, and query:
```json
POST localhost:8080/trips/query
{
"$filter": {
"hvfhs_license_num": "HV0003"
},
"$order_by": {
"trip_miles": "desc"
}
}
```
With configuration:
```yaml
connections:    
- config : !LocalStorage
details:
path: data
tables:
- !Table
name: trips
prefix: /trips
file_type: parquet
extension: .parquet
name: ny_taxi
endpoints:
- name: trips
path: /trips …
```
=> feat: Make secondary index configurable

dozer-orchestrator/src/simple/orchestrator.rs, dozer-types/src/models/api_config.rs, dozer-types/src/tests/api_config_yaml_deserialize.rs, dozer-types/src/tests/postgres_yaml_deserialize.rs
There didn't seem to be any way of disabling either the rest or gRPC apis, this PR adds a new `enabled` flag to both `rest` and `grpc`. If `enabled: false`, the service will not be started at all.
=> feat: allow disabling of grpc & rest apis via config

.github/workflows/dozer-log-python.yml, dozer-log-python/Cargo.toml, dozer-sql/Cargo.toml, dozer-tests/Cargo.toml, dozer-types/Cargo.toml, dozer-types/src/lib.rs, dozer-types/src/types/field.rs
Linux cross compilation doesn't work yet. We're able to build for linux x86_64, all windows and macos now.
=> chore: Add dozer-log-python CI

dozer-log-python/pyproject.toml
to be consistent with the library name.
=> chore: Rename pyproject name from `dozer-log-python` to `pydozer_log`

dozer-cache/src/cache/index/mod.rs, dozer-cache/src/cache/index/tests.rs, dozer-types/src/tests/field_serialize_test.rs, dozer-types/src/types/field.rs, dozer-types/src/types/mod.rs
Because it won't work with `Field::Json` or nested types.
Now composite sorted inverted key comparison is more expensive, we'll introduce other ways of zero-copy deserialization in the future.
=> chore: Remove `FieldBorrow`

dozer-api/src/errors.rs, dozer-api/src/lib.rs, dozer-log-js/src/lib.rs, dozer-log-python/src/lib.rs, dozer-log/src/home_dir.rs, dozer-log/src/schemas.rs, dozer-orchestrator/src/errors.rs, dozer-orchestrator/src/pipeline/builder.rs, dozer-orchestrator/src/pipeline/tests/builder.rs, dozer-orchestrator/src/simple/executor.rs, dozer-orchestrator/src/simple/orchestrator.rs
Closes #1493 
In this PR we don't remove the dozer home dir when dozer runs, instead, we create a new migration directory for every endpoint, and app and api writes to and reads from that directory.
The directory structure is shown in #1488
=> refactor: Start a new migration when dozer restarts

dozer-ingestion/src/connectors/ethereum/trace/tests.rs, dozer-orchestrator/src/pipeline/builder.rs, dozer-orchestrator/src/pipeline/connector_source.rs, dozer-orchestrator/src/pipeline/validate.rs, dozer-orchestrator/src/simple/helper.rs
currently when running the dozer cli, the tables get printed directly to stdout, so they don't respect env logging via `RUST_LOG`. This updates them to use the correct `info!` macro.
=> chore(orchestrator): put the table prints behind info

Cargo.lock, dozer-api/Cargo.toml, dozer-api/src/cache_builder/mod.rs, dozer-api/src/errors.rs, dozer-api/src/lib.rs, dozer-api/src/test_utils.rs, dozer-cache/Cargo.toml, dozer-cache/benches/cache.rs, dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs, dozer-cache/src/cache/lmdb/cache/mod.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/mod.rs, dozer-cache/src/cache/lmdb/cache_manager.rs, dozer-cache/src/cache/lmdb/indexing.rs, dozer-cache/src/cache/lmdb/tests/read_write.rs, dozer-cache/src/cache/lmdb/utils.rs, dozer-cache/src/cache/mod.rs, dozer-log-js/src/lib.rs, dozer-log-python/src/lib.rs, dozer-log/examples/reader.rs, dozer-log/src/reader.rs, dozer-tracing/Cargo.toml, dozer-tracing/src/telemetry.rs, dozer-types/Cargo.toml, dozer-types/src/labels.rs, dozer-types/src/lib.rs, dozer-types/src/models/telemetry.rs
In this PR we support collecting metrics and exporting to Prometheus.
It works by enable it in the configuration:
```yaml
telemetry:
metrics: !Prometheus
```
When enabled, a server listens to `http://0.0.0.0:9000` and returns Prometheus metrics on whatever path.
Example output:
`GET http://0.0.0.0:9000`
```text
build_index{endpoint="trips_cache",migration="v0008",secondary_index="3"} 6869025
build_index{endpoint="trips_cache",migration="v0008",secondary_index="4"} 6868029
build_index{endpoint="trips_cache",migration="v0008",secondary_index="2"} 6869730
build_index{endpoint="trips_cache",migration="v0008",secondary_index="1"} 6870207
build_index{endpoint="trips_cache",migration="v0008",secondary_index="0"} 6870145
build_cache{endpoint="trips_cache",migration="v0008"} 3440478
```
The …
=> feat: Add metrics for cache

dozer-types/protos/cloud.proto
add proto for public service to provide  company metadata 
for example
`dozer cloud login --company acme`
Cli will call this service for getting cognito info related to this company
=> feat: add public service provide metadata for cli: dozer cloud login

dozer-orchestrator/src/cli/cloud.rs, dozer-orchestrator/src/lib.rs, dozer-orchestrator/src/main.rs, dozer-orchestrator/src/simple/cloud_orchestrator.rs, dozer-types/protos/cloud.proto
Added commands:
`dozer cloud version create -a app_id revision`: Creates a new version using given revision
`dozer cloud version set-current -a app_id version`: Sets given version as current
=> feat: Support version management

dozer-cli/src/cli/cloud.rs, dozer-cli/src/main.rs, dozer-cli/src/simple/cloud_orchestrator.rs, dozer-types/protos/cloud.proto
`cloud status` looks like this:
```text
+--------------+---------------------------------------------------------------------+
| Api endpoint | http://company.dev.getdozer.io/8cbece58-7d9c-480a-9b09-aea343554795 |
+--------------+---------------------------------------------------------------------+
| Deployments  | +------------+-----+-----+--------------+                           |
|              | | Deployment | App | Api | Version      |                           |
|              | +============+=====+=====+==============+                           |
|              | | 0          | 🟢  | 2/2 |              |                           |
|              | +------------+-----+-----+--------------+                           |
|              | | 1          | 🟢  | 3/3 | v1 (current) | …
```
=> feat: Add `cloud api set-num-replicas`

Cargo.lock, dozer-cli/Cargo.toml, dozer-cli/src/pipeline/connector_source.rs, dozer-cli/src/pipeline/log_sink.rs, dozer-core/Cargo.toml, dozer-core/src/epoch.rs, dozer-core/src/executor/receiver_loop.rs, dozer-core/src/executor/sink_node.rs, dozer-core/src/forwarder.rs, dozer-types/src/epoch.rs
The`metrics` endpoint looks like this
```text
source_insert{connection="ny_taxi",table="trips"} 208234
pipeline_latency{endpoint="trips_cache",quantile="0"} 0.000089
pipeline_latency{endpoint="trips_cache",quantile="0.5"} 0.00014900956873666247
pipeline_latency{endpoint="trips_cache",quantile="0.9"} 0.00018999742594343942
pipeline_latency{endpoint="trips_cache",quantile="0.95"} 0.00020801506910651807
pipeline_latency{endpoint="trips_cache",quantile="0.99"} 0.0002740225838011025
pipeline_latency{endpoint="trips_cache",quantile="0.999"} 0.0002750108429051483
pipeline_latency{endpoint="trips_cache",quantile="1"} 0.001199
pipeline_latency_sum{endpoint="trips_cache"} 0.02932199999999997
pipeline_latency_count{endpoint="trips_cache"} 184
```
=> feat: Emit metrics of source operations and pipeline latency

Cargo.lock, dozer-sql/Cargo.toml, dozer-sql/src/pipeline/product/join/operator.rs, dozer-sql/src/pipeline/product/join/processor.rs
Emit Join metrics on Prometheus endpoint
```
product_unsatisfied_joins 265
product_output_operations 1887841
product_input_operations 1888106
product_right_lookup_size 265
product_left_lookup_size 254
product_latency{quantile="0"} 0.0000025
product_latency{quantile="0.5"} 0.000040480100968151095
product_latency{quantile="0.9"} 0.000040480100968151095
product_latency{quantile="0.95"} 0.000040480100968151095
product_latency{quantile="0.99"} 0.000040480100968151095
product_latency{quantile="0.999"} 0.00014963672503375144
product_latency{quantile="1"} 0.028400292
product_latency_sum 17.38265707894686
product_latency_count 1888365
```
=> feat: emit Product processor metrics

.github/workflows/dozer-log-python.yml
I removed sccache and it runs fine. We'll lose `pydozer_log` `0.1.24` release but I think that's fine. Nothing has changed from `0.1.23`.
=> chore: Remove maturin sccache because it keeps failing

dozer-api/src/cache_builder/mod.rs, dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs, dozer-cache/src/cache/lmdb/cache/main_environment/operation_log/mod.rs, dozer-cache/src/cache/lmdb/cache/main_environment/operation_log/tests.rs, dozer-cache/src/cache/lmdb/indexing.rs
Example metrics:
```
cache_update{endpoint="trips_cache",migration="v0053"} 18477
build_index{endpoint="trips_cache",migration="v0053",secondary_index="0",secondary_index_type="SortedInverted"} 36979
build_index{endpoint="trips_cache",migration="v0053",secondary_index="1",secondary_index_type="SortedInverted"} 36979
build_index{endpoint="trips_cache",migration="v0053",secondary_index="4",secondary_index_type="SortedInverted"} 36889
build_index{endpoint="trips_cache",migration="v0053",secondary_index="3",secondary_index_type="SortedInverted"} 36979
build_index{endpoint="trips_cache",migration="v0053",secondary_index="2",secondary_index_type="SortedInverted"} 36979
cache_operation{endpoint="trips_cache",migration="v0053"} 36979
cache_insert{endpoint="trips_cache",migration="v0053"} 25
``` …
=> feat: Add more cache metrics

dozer-ingestion/src/connectors/object_store/adapters.rs
chore: add error message for wrong !Table config format for Parquet and CSV
=> chore: add error message for wrong !Table config format for Parquet and CSV

dozer-ingestion/benches/connectors.sample.yaml, dozer-ingestion/src/connectors/object_store/connector.rs, dozer-ingestion/src/connectors/object_store/csv/csv_table.rs, dozer-ingestion/src/connectors/object_store/delta/delta_table.rs, dozer-ingestion/src/connectors/object_store/parquet/parquet_table.rs, dozer-ingestion/src/connectors/object_store/readme.md, dozer-ingestion/src/connectors/object_store/table_reader.rs, dozer-ingestion/src/connectors/object_store/table_watcher.rs, dozer-ingestion/src/connectors/object_store/tests/local_storage_tests.rs, dozer-ingestion/src/connectors/object_store/watcher.rs, dozer-ingestion/src/ingestion/ingestor.rs, dozer-ingestion/tests/test_suite/basic.rs, dozer-ingestion/tests/test_suite/connectors/object_store/local_storage.rs, dozer-tests/src/e2e_tests/cases/dozer-samples-connectors-local-storage/dozer-config.yaml
when we try to uncomment the read() function and try to run both snapshot and watch in the start()
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ObjectStoreConnectorError(InternalDataFusionError(ObjectStore(JoinError { source: JoinError::Cancelled(Id(32)) })))'
```
when we do this
```
tokio::spawn(async move {
connector.start(&ingestor, tables).await.unwrap();
});
```
Tokio tasks are cancelled in two situations:
You call abort on the JoinHandle.
The runtime that you spawned the task on is shut down.
If you do neither of those things, then it wont be cancelled.
=> fix: append only

dozer-sql/Cargo.toml, dozer-sql/src/pipeline/builder.rs, dozer-sql/src/pipeline/errors.rs, dozer-sql/src/pipeline/expression/builder.rs, dozer-sql/src/pipeline/expression/python_udf.rs, dozer-sql/src/pipeline/pipeline_builder/from_builder.rs, dozer-sql/src/pipeline/product/table/factory.rs, dozer-sql/src/pipeline/tests/utils.rs, dozer-tests/Cargo.toml, dozer-tests/src/sql_tests/full/py_udf.test, dozer-tests/src/sql_tests/logic_test.rs
closes #1677
The new syntax was implemented in a local fork of the `sqlparser-rs` crate with a special SQL dialect named `DozerDialect`, which is based on the ANSI dialect. 
Tests have been added as well.
/claim #1677
=> Support for syntax function<Type>() in SQL

dozer-ingestion/src/connectors/snowflake/connection/client.rs
This PR fixes random issues (due to hash map arbitrary ordering). `schemas (HashMap)` was converted into a vector, which had to be ordered in the same way as input `tables_indexes` which wasn't the case due to HashMap arbitrary ordering  and table name ordering `ORDER BY TABLE_NAME, ORDINAL_POSITION`
=> Fix snowflake client fetch_tables ordering

.gitignore, dozer-cli/src/cli/cloud.rs, dozer-cli/src/cloud_app_context.rs, dozer-cli/src/errors.rs, dozer-cli/src/lib.rs, dozer-cli/src/main.rs, dozer-cli/src/simple/cloud_orchestrator.rs
This PR contains changes for cloud commands:
- During first deployment of app, `.dozer-cloud` file is created and app id is stored there
- Context app id can be changed with `dozer cloud app use {app_id}`
- All commands reads app id from context file instead of command args
=> feature: Store app id to context file

dozer-ingestion/Cargo.toml, dozer-ingestion/src/connectors/snowflake/connection/client.rs, dozer-ingestion/src/connectors/snowflake/connector/snowflake.rs, dozer-ingestion/src/connectors/snowflake/stream_consumer.rs, dozer-ingestion/src/connectors/snowflake/test_utils.rs
This PR adds uniq random ID into stream/temp_table name to avoid conflicts running two dozer instances simultaneously
=> Fix snowflake parallel running instances

dozer-api/src/rest/mod.rs, dozer-api/src/rest/tests/routes.rs
https://github.com/getdozer/dozer/issues/1547
Reverse sorts rest endpoints before attaching to app so that overlapping routes are not incorrectly matched.
=> fix: Handle rest path collision

dozer-cli/src/cli/cloud.rs, dozer-cli/src/cli/helper.rs, dozer-cli/src/cli/types.rs, dozer-cli/src/cloud_app_context.rs, dozer-cli/src/errors.rs, dozer-cli/src/lib.rs, dozer-cli/src/main.rs, dozer-cli/src/simple/cloud_orchestrator.rs, dozer-cli/src/simple/migration.rs, dozer-cli/src/simple/orchestrator.rs, dozer-ingestion/README.md, dozer-tests/src/e2e_tests/cases/error_non_existing_primary_key/error.json, dozer-tests/src/e2e_tests/checker/mod.rs, dozer-tests/src/e2e_tests/expectation.rs, dozer-tests/src/e2e_tests/runner/local.rs, dozer-types/src/models/app_config.rs, dozer-types/src/models/cloud.rs
Changes:
- Reorder commands for `cloud` subcommand
- Rename `migrate` to `build`
- Add filter to `connectors` command
- `app run` and `api run` moved to `run` subcommand. Now it is accessible `run app` and `run api`
- Removed `err-threshold` argument
- Hiden `config-token`
- Renamed `company-name` to `organisation-name`
- Create cloud section in app config and store `app_id` in `dozer-cloud.yaml` file
- Combine `cloud update` and `cloud deploy` commands
=> refactor: improve CLI experience

.gitignore, dozer-cli/src/cli/helper.rs, dozer-cli/src/cli/mod.rs, dozer-cli/src/cli/types.rs, dozer-cli/src/cloud_app_context.rs, dozer-cli/src/cloud_helper.rs, dozer-cli/src/config_helper.rs, dozer-cli/src/errors.rs, dozer-cli/src/lib.rs, dozer-cli/src/main.rs, dozer-cli/src/simple/cloud_orchestrator.rs, dozer-tests/src/e2e_tests/case.rs, dozer-types/src/constants.rs
With these changes, we support reading from multiple files. By default, it reads based on two patterns: `dozer-config.*`, `queries/*.sql`
Additionally, user can provide patterns with `-c` parameter, e.g. `-c ./dozer-config.yaml -c ./dozer-config.sources.yaml -c ./queries/simple.sql`
=> feat: Support read of configs from multiple files

rust-toolchain.toml
chore: added toolchain toml to pin version
matching with cloud: https://github.com/getdozer/dozer-cloud/pull/344/files#diff-2b1bde2cf3a858b7bf7424cb8bcbf01f35b94dc80b925d9432cbab3319ca9b4e
=> chore: added toolchain toml to pin version

dozer-log/src/replication/mod.rs, dozer-log/src/replication/tests.rs
Bug senario:
1. Log has in memory ops [0, 499)
2. Log received operation 499 and begins to persist [0, 500)
3. Log received read request [498, 502). Now that [0, 500) is not persisted yet, it decides to add [498, 502) to watcher list.
4. Persisting is done. Now log has persisted [0, 500) and in memory [500, 500)
5. Log received operations 500 and 501. Now it has in memory [500, 502) and decides to trigger the watcher [498, 502), but 498 is not in memory anymore.
We should trigger any watcher that was part of persisted entry before removing in memory ops.
We used to do this, but at the wrong timing. We used to do it before persisting starts. It should happen after persisting is done.
=> fix: Replication log could panic if received request during persisting

dozer-cli/src/main.rs, dozer-core/src/error_manager.rs
Example of config (`dozer-config.telemetry.yaml`)
```
telemetry:
trace: !Jaeger
JaegerTelemetryConfig:
```
=> feat: Register errors from error manager in jaeger

dozer-cli/src/simple/cloud/login.rs
Without truncate partial profile information were left in credentials file (when new details length are shorter than old one)
=> fix: Truncate credentials file when new profiles added or updated

dozer-sql/src/pipeline/aggregation/avg.rs, dozer-sql/src/pipeline/aggregation/max.rs, dozer-sql/src/pipeline/aggregation/max_value.rs, dozer-sql/src/pipeline/aggregation/min.rs, dozer-sql/src/pipeline/aggregation/min_value.rs, dozer-sql/src/pipeline/aggregation/processor.rs, dozer-sql/src/pipeline/aggregation/sum.rs, dozer-sql/src/pipeline/expression/arg_utils.rs, dozer-sql/src/pipeline/expression/case.rs, dozer-sql/src/pipeline/expression/cast.rs, dozer-sql/src/pipeline/expression/comparison.rs, dozer-sql/src/pipeline/expression/conditional.rs, dozer-sql/src/pipeline/expression/datetime.rs, dozer-sql/src/pipeline/expression/execution.rs, dozer-sql/src/pipeline/expression/geo/distance.rs, dozer-sql/src/pipeline/expression/geo/point.rs, dozer-sql/src/pipeline/expression/in_list.rs, dozer-sql/src/pipeline/expression/json_functions.rs, dozer-sql/src/pipeline/expression/logical.rs, dozer-sql/src/pipeline/expression/mathematical.rs, dozer-sql/src/pipeline/expression/python_udf.rs, dozer-sql/src/pipeline/expression/scalar/common.rs, dozer-sql/src/pipeline/expression/scalar/number.rs, dozer-sql/src/pipeline/expression/scalar/string.rs, dozer-sql/src/pipeline/expression/tests/execution.rs, dozer-sql/src/pipeline/planner/projection.rs, dozer-sql/src/pipeline/projection/factory.rs, dozer-sql/src/pipeline/projection/processor.rs, dozer-sql/src/pipeline/selection/processor.rs, dozer-sql/src/pipeline/table_operator/lifetime.rs
It's only implemented by `Expression`
=> chore: Remove unused trait `ExpressionExecutor`.

dozer-cli/src/cli/cloud.rs, dozer-cli/src/lib.rs, dozer-cli/src/main.rs, dozer-cli/src/simple/cloud/login.rs, dozer-cli/src/simple/cloud_orchestrator.rs, dozer-tracing/src/telemetry.rs
These changes allow to use login without questions
```
dozer cloud login --organisation-name {name} --profile-name {profile_name} --client-id {client_id} --client-secret {client_secret}
```
=> feat: Allow to use client properties in login command

README.md
Tiny capitalization fix in README.md: `Javascript` -> `JavaScript` ;)
=> Fix JavaScript capitalization

dozer-ingestion/Cargo.toml, dozer-ingestion/src/connectors/mod.rs, dozer-ingestion/src/connectors/mysql/binlog.rs, dozer-ingestion/src/connectors/mysql/connector.rs, dozer-ingestion/src/connectors/mysql/conversion.rs, dozer-ingestion/src/connectors/mysql/helpers.rs, dozer-ingestion/src/connectors/mysql/mod.rs, dozer-ingestion/src/connectors/mysql/schema.rs, dozer-ingestion/src/errors.rs, dozer-tests/src/e2e_tests/cases/mysql-chinook/dozer-config.yaml, dozer-tests/src/e2e_tests/cases/mysql-chinook/expectations.json, dozer-tests/src/e2e_tests/connections/chinook_mysql/Dockerfile, dozer-tests/src/e2e_tests/connections/chinook_mysql/download.sh, dozer-tests/src/e2e_tests/connections/chinook_mysql/is_ready.sh, dozer-tests/src/e2e_tests/connections/chinook_mysql/service.yaml, dozer-tests/src/e2e_tests/runner/running_env.rs, dozer-types/src/ingestion_types.rs, dozer-types/src/models/connection.rs
Define and implement a MySQL connector for Dozer. 
It operates similarly to the Postgres connector; especially when it comes to listing tables, columns, and schemas.
For replication, MySQL CDC is used to replay database changes in Dozer, after initially copying the table contents with a simple SELECT query.
The connector implementation is pretty much complete with the only exception of partial updates to JSON fields, which is a feature in MySQL that does not have pre-existing support in Dozer as far as I could tell.
closes #1670
/claim #1670
=> feat: Introduce MySQL Connector

.github/workflows/coverage.yaml
A local MySQL service is required to run some integration tests in the coverage CI workflow.
=> test: provide a MySQL service for CI coverage tests

.github/labeler.yml, .github/workflows/labeler.yml
Resolves: #1882 
Create a Github Action that runs on certain file changes and labels a PR as doc-update-needed.
Uses: https://github.com/marketplace/actions/labeler
Add label 'doc-update-needed' for:
- dozer-types/src/models/*
- dozer-cli/src/cli/types.rs
- dozer-types/protos/*
- dozer-api/src/generator/protoc/generator/template/proto.tmpl
This was tested in my forked repository:
See: https://github.com/tungbq/dozer/pulls
=> ci: introduce labeler workflow

README.md
Update the current state of the MySQL connector in `README.md`, and point to the MySQL connector example in the `dozer-samples` repo.
=> docs: advertise support for the MySQL connector

dozer-cli/src/pipeline/connector_source.rs
As @chubei noted, in the case of `CdcType::FullChanges` the CDC backend provides the old values as well as the new values of a change; therefore, dozer does not need to keep track of the old record; hence, the primary key should not be required.
=> fix: do not require primary key for CdcType::FullChanges

Cargo.lock, dozer-tests/Cargo.toml, dozer-tests/src/sql_tests/arg.rs, dozer-tests/src/sql_tests/logic_test.rs, dozer-tests/src/sql_tests/validator.rs
Makes filtering sql test behave the same as filtering `libtest` tests and makes the output look like `libtest`.
In general, this is in the "less surprising" category.
=> Run sql-tests with custom libtest-mimic harness

dozer-cli/src/lib.rs, dozer-cli/src/live/state.rs, dozer-cli/src/pipeline/builder.rs, dozer-cli/src/pipeline/tests/builder.rs, dozer-cli/src/simple/executor.rs, dozer-cli/src/simple/orchestrator.rs, dozer-cli/src/ui_helper.rs, dozer-core/src/app.rs, dozer-core/src/tests/app.rs, dozer-sql/src/pipeline/aggregation/factory.rs, dozer-sql/src/pipeline/aggregation/processor.rs, dozer-sql/src/pipeline/aggregation/tests/aggregation_test_planner.rs, dozer-sql/src/pipeline/aggregation/tests/aggregation_tests_utils.rs, dozer-sql/src/pipeline/builder.rs, dozer-sql/src/pipeline/mod.rs, dozer-sql/src/pipeline/pipeline_builder/join_builder.rs, dozer-sql/src/pipeline/product/join/factory.rs, dozer-sql/src/pipeline/product/join/operator.rs, dozer-sql/src/pipeline/product/set/mod.rs, dozer-sql/src/pipeline/product/set/operator.rs, dozer-sql/src/pipeline/product/set/record_map.rs, dozer-sql/src/pipeline/product/set/set_factory.rs, dozer-sql/src/pipeline/product/set/set_processor.rs, dozer-sql/src/pipeline/tests/builder_test.rs, dozer-sql/src/pipeline/utils/mod.rs, dozer-sql/src/pipeline/utils/record_hashtable_key.rs, dozer-tests/src/sql_tests/helper/pipeline.rs, dozer-types/protos/cloud_types.proto, dozer-types/src/models/flags.rs, dozer-types/src/tests/flags_config_yaml_deserialize.rs
Resolves #1875. 
Probabilistic optimization sacrifices accuracy in order to reduce memory consumption. In certain parts of the pipeline, a Bloom Filter is used ([set_processor](https://github.com/getdozer/dozer/blob/2e3ba96c3f4bdf9a691747191ab15617564d8ca2/dozer-sql/src/pipeline/product/set/set_processor.rs#L20)), while in other parts, hash tables that store only the hash of the keys instead of the full keys are used ([aggregation_processor](https://github.com/getdozer/dozer/blob/2e3ba96c3f4bdf9a691747191ab15617564d8ca2/dozer-sql/src/pipeline/aggregation/processor.rs#L59) and [join_processor](https://github.com/getdozer/dozer/blob/2e3ba96c3f4bdf9a691747191ab15617564d8ca2/dozer-sql/src/pipeline/product/join/operator.rs#L57-L58)).
This PR makes these optimizations disabled by default and …
=> feat: make probabilistic optimizations optional and tunable in the config

.github/workflows/coverage.yaml, .github/workflows/setup-mysql-and-mariadb/action.yaml
The MySQL connector should be tested against MariaDB as well, because it has been failing recently on MariaDB.
#1867 depends on this.
=> chore: setup MySQL and MariaDB services in the CI

.gitignore, dozer-cli/src/cli/helper.rs, dozer-cli/src/errors.rs, dozer-cli/src/simple/build/contract/mod.rs, dozer-cli/src/simple/build/mod.rs, dozer-cli/src/simple/executor.rs, dozer-cli/src/simple/orchestrator.rs, dozer-ingestion/tests/test_suite/connectors/dozer.rs, dozer-log/src/home_dir.rs, dozer-tests/src/e2e_tests/runner/local.rs, dozer-tests/src/tests/e2e/mod.rs, dozer-types/src/constants.rs, dozer-utils/src/cleanup.rs
Currently, this always writes the lock file to the current working directory.
Ideally we would follow the `dozer-config.yaml` around, but that is currently
impractical because of the implementation of the `-c` flag, combining `*.sql` and
`dozer-config.*`.
=> Write dozer.lock

Cargo.lock, dozer-api/Cargo.toml, dozer-api/src/rest/api_generator.rs, dozer-cache/Cargo.toml, dozer-cache/src/cache/expression/mod.rs
Two changes:
- Implement `FromRequest` for a newtype `QueryExpressionExtractor` to avoid make `dozer-cache` depend on `actix-web`
- Use `Either` instead of `LocalBoxFuture` to avoid allocation
=> chore: Refactor `QueryExpression` extractor implementation

dozer-core/src/epoch/manager.rs, dozer-core/src/epoch/mod.rs, dozer-core/src/executor/receiver_loop.rs, dozer-core/src/forwarder.rs
I believe the merging was in `ReceiverLoop` because the `SourceStates` was introduced before `EpochManager`, and every source sent commit messages independently. In that case, `ReceiverLoop`s (processors and sinks) are the only place to merge source states.
Now that we have `EpochManager`, it makes more sense to merge once only in it.
=> chore: Remove source state merging from `ReceiverLoop` to `EpochManager`

dozer-ingestion/src/connectors/mysql/connection.rs
Reference: https://dev.mysql.com/doc/refman/8.0/en/select.html#:~:text=To%20retrieve%20all,%2C18446744073709551615%3B
=> fix: mysql select query offset syntax is wrong

dozer-api/src/api_helper.rs, dozer-api/src/grpc/client_server.rs, dozer-api/src/rest/mod.rs, dozer-cli/src/live/server.rs, dozer-cli/src/live/state.rs, dozer-cli/src/main.rs, dozer-cli/src/simple/orchestrator.rs, dozer-types/build.rs, dozer-types/protos/api_explorer.proto, dozer-types/protos/contract.proto, dozer-types/protos/live.proto, dozer-types/src/grpc_types.rs
=> chore: read env DOZER_MASTER_SECRET for api security

dozer-log/src/storage/mod.rs
Because the `Display` implementation is not very useful
=> chore: Debug print aws sdk errors

dozer-ingestion/src/connectors/delta_lake/connector.rs, dozer-ingestion/src/connectors/delta_lake/test/deltalake_test.rs, dozer-ingestion/src/connectors/dozer/connector.rs, dozer-ingestion/src/connectors/ethereum/log/connector.rs, dozer-ingestion/src/connectors/ethereum/log/tests/helper.rs, dozer-ingestion/src/connectors/ethereum/trace/connector.rs, dozer-ingestion/src/connectors/ethereum/trace/tests.rs, dozer-ingestion/src/connectors/grpc/connector.rs, dozer-ingestion/src/connectors/kafka/connector.rs, dozer-ingestion/src/connectors/mod.rs, dozer-ingestion/src/connectors/mongodb/mod.rs, dozer-ingestion/src/connectors/mysql/connector.rs, dozer-ingestion/src/connectors/object_store/connector.rs, dozer-ingestion/src/connectors/object_store/tests/local_storage_tests.rs, dozer-ingestion/src/connectors/postgres/connector.rs, dozer-ingestion/src/connectors/snowflake/connector/snowflake.rs, dozer-ingestion/src/connectors/snowflake/stream_consumer.rs, dozer-ingestion/src/connectors/snowflake/tests.rs, dozer-ingestion/src/ingestion/ingestor.rs, dozer-ingestion/tests/test_suite/basic.rs
Make the the blocking snowflake connector `async` in the most straightforward way, which is to move blocking code to a separate thread with `spawn_blocking`.
Alternatives considered to the current snowflake client in use:
- [odbc-api](https://lib.rs/crates/odbc-api): async support is limited. connections are still blocking, as well as getting schemas.
- [snowflake-api](https://lib.rs/crates/snowflake-api): relies on undocumented snowflake apis, which may or may not break in the future.
- [snowflake-connector](https://lib.rs/crates/snowflake-connector): still "Under heavy development".
=>  fix: make snowflake connector async

dozer-ingestion/src/connectors/postgres/connection/helper.rs
Postgres occasionally sends a timeout error. We should retry.
=> fix: handle a postgres timeout error

dozer-ingestion/src/connectors/snowflake/connection/client.rs, dozer-ingestion/src/errors.rs
There is only one instance where a query which returns multiple rows is not a SELECT query in the snowflake connector. We can restart the query when a network error occurs.
=> fix: resume a non-SELECT query in snowflake connector

Cargo.lock, dozer-ingestion/Cargo.toml, dozer-ingestion/src/connectors/snowflake/connection/client.rs, dozer-ingestion/src/connectors/snowflake/connection/helpers.rs
I introduced a few bugs in the last network error handling pull request. These are fixes for them.
=> fix: snowflake bug fixes

dozer-ingestion/src/connectors/mysql/connector.rs
MySQL returns an error if two clients are using the same `server_id` concurrently.
=> fix: mysql use a random server_id if none was specified

dozer-ingestion/src/connectors/snowflake/connection/client.rs, dozer-ingestion/src/connectors/snowflake/stream_consumer.rs
Start the query exec iterator to get a valid schema. The iterator is considered empty if the schema is `None`.
=> fix: snowflake regression

dozer-cli/src/simple/cloud/deployer.rs, dozer-cli/src/simple/cloud_orchestrator.rs
Stopping application will be done on cloud side during application deletion
=> chore: Remove stop application call when deleting application

dozer-cli/src/cli/cloud.rs, dozer-cli/src/cloud/client.rs, dozer-cli/src/cloud/login.rs, dozer-cli/src/cloud/mod.rs, dozer-cli/src/errors.rs, dozer-cli/src/main.rs
previous PR didnt handle errors fully https://github.com/getdozer/dozer/commit/ba1df9df7dbc981083bc2bf1d797e5f95104f203
Needed to not even initialize configuration and run cloud within the scope of telemetry for logging.
=> chore: handle cloud client creation

dozer-cli/src/live/state.rs, dozer-cli/src/utils.rs, dozer-core/src/checkpoint/mod.rs, dozer-core/src/epoch/manager.rs, dozer-core/src/epoch/mod.rs, dozer-core/src/executor/receiver_loop.rs, dozer-core/src/executor/sink_node.rs, dozer-recordstore/src/in_memory/store.rs, dozer-recordstore/src/lib.rs, dozer-recordstore/src/rocksdb.rs, dozer-types/src/models/flags.rs, json_schemas/dozer.json
This PR adds a new flag `enable_app_checkpoints`. When disabled, `EpochManager` stops creating `CheckpointWriter`s, effectively avoids persisting the processor record store, all processors and the record writer. A new field `sink_persist_queue` is added to `EpochCommonInfo` to continue persisting the log even if checkpoints are disabled.
This flag defaults to `false`, which means the checkpoints are disabled.
=> feat: Add a config to disable pipeline checkpointing by default

dozer-cli/src/cli/cloud.rs
Before we only allow syntax like `-s ENV_VAR_NAME=ENV_VAR_VALUE`. Now we also support `-s ENV_VAR_NAME` if the env var is present locally.
=> feat: Allow passing environment variable name as secrets

dozer-cli/src/simple/orchestrator.rs
We'll only have one instance of this channel, so a (semi-)large size should be okay.
The smaller size caused some messages to be dropped in the case of joins
with a large fan-out.
We could eventually expose OnEvent using log readers instead, which means we 
would not have to keep any messages in memory for OnEvent at all.
=> Increase OnEvent operation channel size

dozer-api/src/cache_builder/mod.rs, dozer-api/src/test_utils.rs, dozer-cache/benches/cache.rs, dozer-cache/src/cache/lmdb/cache/dump_restore.rs, dozer-cache/src/cache/lmdb/cache/main_environment/conflict_resolution_tests.rs, dozer-cache/src/cache/lmdb/cache/main_environment/dump_restore.rs, dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs, dozer-cache/src/cache/lmdb/cache/mod.rs, dozer-cache/src/cache/lmdb/cache/query/tests.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/dump_restore.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/indexer.rs, dozer-cache/src/cache/lmdb/tests/basic.rs, dozer-cache/src/cache/lmdb/tests/read_write.rs, dozer-cache/src/cache/mod.rs, dozer-cli/src/pipeline/log_sink.rs, dozer-log/src/errors.rs, dozer-log/src/reader.rs, dozer-log/src/replication/mod.rs, dozer-log/src/replication/tests.rs, dozer-tests/src/cache_tests/film/load_database.rs
This PR is a preparation for solving the log data loss problem.
- We store `SourceStates` in cache, so when cache reconnects to a log, it knows whether it needs to roll back.
- We keep track of the `SourceStates` that was persisted when a `Log` is restored from checkpoint, so a reconnecting client knows where to roll back to if necessary.
=> feat: Store `SourceStates` in log and cache

dozer-api/src/cache_builder/mod.rs, dozer-api/src/test_utils.rs, dozer-cache/benches/cache.rs, dozer-cache/src/cache/lmdb/cache/dump_restore.rs, dozer-cache/src/cache/lmdb/cache/main_environment/conflict_resolution_tests.rs, dozer-cache/src/cache/lmdb/cache/main_environment/dump_restore.rs, dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs, dozer-cache/src/cache/lmdb/cache/mod.rs, dozer-cache/src/cache/lmdb/cache/query/tests.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/dump_restore.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/indexer.rs, dozer-cache/src/cache/lmdb/tests/basic.rs, dozer-cache/src/cache/lmdb/tests/read_write.rs, dozer-cache/src/cache/mod.rs, dozer-tests/src/cache_tests/film/load_database.rs
This is a follow-up to https://github.com/getdozer/dozer/pull/2158. We shouldn't have used two different databases because the two pieces of information always appear together.
=> refactor: Store source states and log position in one database

dozer-api/src/cache_builder/mod.rs, dozer-api/src/lib.rs, dozer-api/src/test_utils.rs, dozer-cache/benches/cache.rs, dozer-cache/src/cache/lmdb/cache/dump_restore.rs, dozer-cache/src/cache/lmdb/cache/main_environment/conflict_resolution_tests.rs, dozer-cache/src/cache/lmdb/cache/main_environment/dump_restore.rs, dozer-cache/src/cache/lmdb/cache/main_environment/hash_tests.rs, dozer-cache/src/cache/lmdb/cache/main_environment/mod.rs, dozer-cache/src/cache/lmdb/cache/main_environment/operation_log/mod.rs, dozer-cache/src/cache/lmdb/cache/main_environment/operation_log/tests.rs, dozer-cache/src/cache/lmdb/cache/mod.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/dump_restore.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/mod.rs, dozer-cache/src/cache/lmdb/cache_manager.rs, dozer-cache/src/cache/lmdb/indexing.rs, dozer-cache/src/cache/lmdb/tests/read_write.rs, dozer-cache/src/cache/lmdb/tests/utils.rs, dozer-cache/src/cache/lmdb/utils.rs, dozer-cache/src/cache/mod.rs, dozer-cache/src/errors.rs, dozer-cache/src/main.rs, dozer-tests/src/cache_tests/film/load_database.rs
Every cache is a file under the `cache_dir`. Previously we're using the metrics labels as the cache file name. This works when there's a unique cache for each endpoint.
However, as we're going to introduce blue green cache again, this naming convention can not be used anymore.
Here we add a `name` parameter to `RwCacheManager::create_cache`, to allow the user to use a different name from the labels. The labels only affects the metrics labels now. And we can open the same cache while attaching different labels.
The plan is to use the labels as cache alias to enable switching between blue green cache.
=> feat: Split cache name and label

dozer-sql/expression/src/aggregate.rs, dozer-sql/src/aggregation/aggregator.rs, dozer-sql/src/aggregation/max.rs, dozer-sql/src/aggregation/min.rs, dozer-sql/src/aggregation/tests/aggregation_min_tests.rs
This makes use of the fact that the output value of the aggregator will
always be of the same, predetermined type. Therefore, there is no use in
storing the type of the output for every record in the state.
`Field` is 32 bytes, whereas the most common types for the outputs (u64
and float) are 8 bytes. In those cases this changes saves about 3/4 of
the memory.
MinValue and MaxValue require some more work, and are therefore not included
in this PR, but the same principle applies there.
=> Reduce memory usage of min and max aggregators

dozer-api/Cargo.toml, dozer-api/src/cache_builder/builder_impl.rs, dozer-api/src/cache_builder/endpoint_meta.rs, dozer-api/src/cache_builder/mod.rs, dozer-api/src/errors.rs, dozer-api/src/generator/protoc/mod.rs, dozer-api/src/grpc/internal/internal_pipeline_server.rs, dozer-api/src/lib.rs, dozer-cli/src/simple/build/mod.rs, dozer-cli/src/simple/executor.rs, dozer-cli/src/simple/orchestrator.rs, dozer-ingestion/src/connectors/dozer/connector.rs, dozer-log/src/home_dir.rs, dozer-log/src/reader.rs, dozer-types/protos/internal.proto
- `build_name` is not necessary because we always build to `v0001`.
- `descriptor_bytes` is not necessary because it's generated from schema.
=> chore: Remove legacy `build_name` and `descriptor_bytes` from `EndpointMeta`

dozer-core/src/checkpoint/mod.rs, dozer-core/src/epoch/manager.rs, dozer-recordstore/src/in_memory/store.rs
This field is not necessary and was not correctly maintained in `deserialize_and_extend`
=> fix: Remove redundant `idx` in `ProcessorRecordStore`

dozer-core/src/checkpoint/mod.rs, dozer-recordstore/src/in_memory/store.rs
`ProcessorRecordStore::serialize_slice` used to return the number of records serialized. The returned value is used to determine the `start` parameter of the next call to `ProcessorRecordStore::serialize_slice`.
However, after we introduce `ProcessorRecordStore::vacuum`, it no longer makes sense and results in duplicated serialization. Here we change the return value to the proper `start` value of next call to `ProcessorRecordStore::serialize_slice`.
=> fix: `ProcessorRecordStore::serialize_slice` was returning wrong length

dozer-cache/src/cache/index/mod.rs, dozer-cache/src/cache/lmdb/cache/secondary_environment/comparator.rs
Note that this comparator will be much slower than before because it involves allocation for `string` and `json` types.
Fixes #1979
=> fix: Stop lexically compare secondary index key

dozer-api/src/cache_builder/builder_impl.rs, dozer-api/src/cache_builder/endpoint_meta.rs, dozer-api/src/cache_builder/mod.rs
We used log id as the cache name in https://github.com/getdozer/dozer/pull/2162. When there are multiple endpoints, caches of different endpoints will have the same name, which is just wrong.
=> fix: Cache name is not unique when there are multiple endpoints

.github/workflows/release.yaml
Problem was introduced in #2189. 
After this fix, the action runs successfully https://github.com/getdozer/dozer/actions/runs/6708158427/job/18228317195
=> fix: Include `-p` parameter in cross build to avoid building web3

Cargo.lock, dozer-cli/src/pipeline/builder.rs, dozer-cli/src/pipeline/connector_source.rs, dozer-cli/src/pipeline/tests/builder.rs, dozer-cli/src/simple/orchestrator.rs, dozer-ingestion/Cargo.toml, dozer-ingestion/benches/helper.rs, dozer-ingestion/javascript/Cargo.toml, dozer-ingestion/javascript/src/js_extension/ingest.js, dozer-ingestion/javascript/src/js_extension/mod.rs, dozer-ingestion/javascript/src/js_extension/tests.rs, dozer-ingestion/javascript/src/js_extension/ts_module_loader.rs, dozer-ingestion/javascript/src/lib.rs, dozer-ingestion/src/lib.rs, dozer-tests/src/e2e_tests/runner/running_env.rs, dozer-types/src/models/connection.rs, dozer-types/src/models/ingestion_types.rs, json_schemas/connections.json, json_schemas/dozer.json
We implement a custom Deno op `ingest`. Users can call that to ingest any JSON data to Dozer.
Use code runs in an embedded Deno runtime.
=> feat: deno connector

.github/workflows/release.yaml, dozer-log-js/package-lock.json, dozer-log-js/package.json
The macos x64 release workflow fails because of timeout. If removing timeout works, we'll release `0.2.1`.
`dozer-log-js` `0.2.0` was not released because of the missing version bump. We'll skip it.
=> fix: Bump `dozer-log-js` version. Remove release workflow timeout

.github/workflows/dozer.yaml, .github/workflows/release.yaml
`hashFile (Cargo.lock)` was not a good cache key. We replace them with `rust-cache`.
We're not sure what happened to the `.deb` release. Looks like the depended action has behaviour changes. After this fix, it works again. A successful run: https://github.com/getdozer/dozer/actions/runs/6735239232/job/18307959724. The artifacts: https://github.com/getdozer/dozer/releases/tag/dev
=> fix: Use `rust-cache` and fix `.deb` release

dozer-sql/expression/src/case.rs, dozer-sql/expression/src/cast.rs, dozer-sql/expression/src/comparison/mod.rs, dozer-sql/expression/src/comparison/tests.rs, dozer-sql/expression/src/conditional.rs, dozer-sql/expression/src/datetime.rs, dozer-sql/expression/src/execution.rs, dozer-sql/expression/src/geo/common.rs, dozer-sql/expression/src/geo/distance.rs, dozer-sql/expression/src/geo/point.rs, dozer-sql/expression/src/in_list.rs, dozer-sql/expression/src/json_functions.rs, dozer-sql/expression/src/logical.rs, dozer-sql/expression/src/mathematical/mod.rs, dozer-sql/expression/src/mathematical/tests.rs, dozer-sql/expression/src/onnx/udf.rs, dozer-sql/expression/src/operator.rs, dozer-sql/expression/src/python_udf.rs, dozer-sql/expression/src/scalar/common.rs, dozer-sql/expression/src/scalar/number.rs, dozer-sql/expression/src/scalar/string.rs, dozer-sql/src/aggregation/processor.rs, dozer-sql/src/expression/tests/execution.rs, dozer-sql/src/projection/processor.rs, dozer-sql/src/table_operator/lifetime.rs, dozer-sql/src/table_operator/operator.rs, dozer-sql/src/table_operator/tests/operator_test.rs
As decided in https://github.com/getdozer/dozer/discussions/2212, functions can be stateful. It follows that the evaluation of the function should take `&mut self`, otherwise the state cannot mutate.
All other changes are just compilation error fixes.
=> chore: Make `Expression::evaluate` accept `&mut self`

dozer-cli/src/main.rs, dozer-cli/src/simple/orchestrator.rs
`dozer run app` runs app + lambda. `dozer run` runs app + lambda + api. `dozer run lambda` still runs lambda only.
=> feat: Include lambda running in app

Cargo.lock, dozer-api/Cargo.toml, dozer-api/src/rest/api_generator.rs, dozer-api/src/sql/datafusion/json.rs, dozer-api/src/sql/datafusion/mod.rs, dozer-api/src/sql/mod.rs, dozer-api/src/sql/pgwire.rs, dozer-api/src/sql/util.rs, dozer-tests/src/cache_tests/filter.rs, dozer-types/Cargo.toml, dozer-types/src/json_types.rs
To properly serialize decimal data types, we enable the `arbitrary_precision` feature from `serde_json` and do our own JSON conversion from `datafusion`'s `RecordBatch`es to JSON.
=> fix: json conversion of Decimal doesn't work with arrow-json

dozer-sql/expression/src/cast.rs, dozer-sql/expression/src/datetime.rs, dozer-sql/src/expression/tests/cast.rs, dozer-types/src/types/field.rs, dozer-types/src/types/tests.rs
Changes to support SQL timestamp to date casting and usage of days interval
```sql
SELECT CAST((NOW() - INTERVAL '365' day) as date) ....
```
=> feat: Add casting from timestamp to date

dozer-api/src/rest/api_generator.rs
Currently, the REST list endpoint `/` returns a maximum of 50 records, regardless of the configured default limit.
=> fix: use default_max_num_records in list REST endpoint

dozer-ingestion/postgres/src/connector.rs, dozer-ingestion/postgres/src/snapshotter.rs
Previously, it was not possible to ingest from postgres tables with a
name containing uppercase characters, because in SQL, unquoted names are
normalized.
=> Fix: make postgres connector schema and table names case-sensitive

Cargo.lock, dozer-ingestion/mysql/Cargo.toml, dozer-ingestion/mysql/src/binlog.rs, dozer-ingestion/mysql/src/connector.rs, dozer-ingestion/mysql/src/conversion.rs, dozer-ingestion/mysql/src/lib.rs, dozer-ingestion/mysql/src/schema.rs
Handle schema changes in MySQL connector.
Breaking schema changes stop the ingestion with an error. Non-breaking schema changes do not affect ingestion.
Breaking changes are:
- Dropping or renaming a database, table, or a column in a table that is being ingested
- Change in the data-type of a column that is being ingested that results in a different dozer field data-type.
Non-breaking changes are:
- Column reordering
- Addition of columns
- Dropping or renaming databases, columns, and tables that are not being ingested
- Superficial change in column data-type such that the dozer field data-type is unchanged
Implementation notes:
`sqlparser` is used for parsing `ALTER TABLE` SQL queries from MySQL Binlog to determine the type of schema change that occurred, and choose an appropriate …
=> feat: handle breaking and non-breaking schema changes for MySQL connector

dozer-cli/src/simple/orchestrator.rs, dozer-deno/src/runtime/exception.js, dozer-deno/src/runtime/fetch.js, dozer-deno/src/runtime/fetch_exception.js, dozer-deno/src/runtime/mod.rs, dozer-deno/src/runtime/square.js, dozer-deno/src/runtime/tests.rs, dozer-lambda/src/js/mod.rs, dozer-lambda/src/js/tests.rs, dozer-lambda/src/js/worker/mod.rs, dozer-sql/expression/src/javascript/evaluate.rs
It turns out when we do `async` things in JavaScript, Deno spawns futures to the tokio runtime that it runs in, and it always assumes that all futures run in the same thread.
As a result, we must use a separate tokio runtime for running JavaScript code, otherwise futures get scheduled to other threads and code panics or segfault.
Depends on #2230
=> feat: Support async lambda and udf

Cargo.lock, dozer-deno/src/runtime/js_runtime.rs, dozer-deno/src/runtime/mod.rs, dozer-deno/src/runtime/tests.rs, dozer-ingestion/javascript/src/js_extension/tests.rs, dozer-lambda/src/js/worker/mod.rs, dozer-sql/expression/Cargo.toml, dozer-sql/expression/src/execution.rs, dozer-sql/expression/src/javascript/evaluate.rs, dozer-sql/src/aggregation/factory.rs, dozer-sql/src/aggregation/processor.rs, dozer-sql/src/projection/factory.rs, dozer-sql/src/projection/processor.rs, dozer-sql/src/selection/factory.rs, dozer-sql/src/selection/processor.rs
This PR does two things:
- Add an Deno extension that exposes two ops to the javascript UDF: `get_state` and `set_state`.
- All the processors serialize the set state during checkpointing, and restore the state during processor construction.
UDF implementors should use the `state` APIs to ensure correct behaviour across pipeline restarts.
An example UDF that outputs the fibonacci sequence can be implemented like this:
```javascript
const { get_state, set_state } = Deno.core.ops;
export default function () {
const { previous, current } = get_state() || { previous: 0, current: 1 };
const next = previous + current;
set_state({ previous: current, current: next });
return current;
}
```
Consider following implementation that doesn't persist state:
```javascript
let previous = 0;
let current = …
```
=> feat: Support stateful javascript UDF

Cargo.lock, dozer-api/src/grpc/internal/internal_pipeline_server.rs, dozer-cli/src/pipeline/dummy_sink.rs, dozer-cli/src/pipeline/log_sink.rs, dozer-cli/src/simple/executor.rs, dozer-cli/src/simple/orchestrator.rs, dozer-core/src/checkpoint/mod.rs, dozer-core/src/errors.rs, dozer-core/src/executor/sink_node.rs, dozer-core/src/node.rs, dozer-core/src/tests/dag_base_errors.rs, dozer-core/src/tests/sinks.rs, dozer-lambda/src/js/tests.rs, dozer-log/Cargo.toml, dozer-log/src/reader/checkpoint.rs, dozer-log/src/reader/mod.rs, dozer-log/src/replication/mod.rs, dozer-log/src/replication/persist.rs, dozer-log/src/replication/tests.rs, dozer-sql/src/tests/builder_test.rs, dozer-tests/src/sql_tests/helper/pipeline.rs, dozer-types/protos/internal.proto
This PR adds `CheckpointedLogReader` which only reads the checkpointed log entries, hence ensuring exact once semantics.
It's not backward compatible because it changes the log entry naming convention to include epoch id in the name.
=> feat: Add `CheckpointedLogReader`

dozer-cli/src/cli/helper.rs, dozer-cli/src/cli/init.rs, dozer-cli/src/config_helper.rs, dozer-cli/src/live/state.rs, dozer-cli/src/main.rs, dozer-cli/src/simple/helper.rs, dozer-cli/src/simple/orchestrator.rs, dozer-tests/src/e2e_tests/case.rs
- Log loaded config files
- Remove printing logo
- Rename Home directory to Data directory in user-facing messages
- Initiating -> Initializing
=> Various fixes for CLI output

dozer-cli/src/pipeline/connector_source.rs, dozer-core/src/builder_dag.rs, dozer-core/src/executor/source_node.rs, dozer-core/src/node.rs, dozer-core/src/tests/app.rs, dozer-core/src/tests/dag_base_create_errors.rs, dozer-core/src/tests/dag_base_errors.rs, dozer-core/src/tests/dag_ports.rs, dozer-core/src/tests/dag_schemas.rs, dozer-core/src/tests/sources.rs, dozer-sql/src/tests/builder_test.rs, dozer-tests/src/sql_tests/helper/pipeline.rs
This is the preparation for changing connectors to pull model.
=> chore: Move `last_checkpoint` from `Source::start` to `SourceFactory::build`

dozer-ingestion/postgres/src/helper.rs, dozer-ingestion/postgres/src/lib.rs
These changes in date parsing allowed an increase in throughput of CDC stream processing from 55k/s to 100k/s for the same data.
=> fix: Improve performance of date parsing

Cargo.lock, dozer-ingestion/postgres/Cargo.toml, dozer-ingestion/postgres/src/helper.rs, dozer-ingestion/postgres/src/schema/tests.rs, dozer-ingestion/postgres/src/snapshotter.rs, dozer-ingestion/postgres/src/tests/client.rs
The match on type was not properly optimized, so manually make a lookup
table for data conversion routines.
Also pre-allocate the full fields vector.
These changes together improve throughput by about 9%.
As we probably want to move to a different method for snapshotting altogether,
feel free to close this PR, but it might be nice inspiration for possible 
optimizations.
=> Optimize postgres snapshotting

dozer-sql/src/projection/processor.rs, dozer-sql/src/selection/processor.rs, dozer-sql/src/table_operator/processor.rs, dozer-sql/src/window/processor.rs
Following processors are stateless:
- Projection
- Selection
- Window
- TTL
Following config has the same throughput as without the sql:
```yaml
app_name: dozer-pg-sample
version: 1
connections:
- name: dozer_pg_db
config: !Postgres
user: chubei
password: postgres
host: localhost
port: 5432
database: bench_2
sql: SELECT * INTO output FROM pgbench_accounts;
endpoints:
- table_name: output
kind: !Dummy
```
Closes #2311
=> feat: Implement batch processing for stateless processors

Cargo.lock, dozer-sink-aerospike/Cargo.toml, dozer-sink-aerospike/aerospike-client-sys/build.rs, dozer-sink-aerospike/src/lib.rs, dozer-types/src/models/endpoint.rs, json_schemas/dozer.json
- Fix aerospike sink build if gcov is not found
- Add multi-threading to aerospike sink
Quite diminished performance with 2 and 3 threads, but barely any hit for 1 thread
and steadily increased performance for up to `available_parallelism()` threads.
=> Add aerospike sink multithreading

dozer-sink-aerospike/aerospike-client-sys/build.rs
The default bindgen cargo hooks hook on code generated by the build script, which means `aerospike-client-sys` will always rebuild. This commit changes that to use the original sources instead for checking for changes.
=> Fix spurious rebuilds for aerospike sink

Cargo.lock, dozer-ingestion/oracle/Cargo.toml, dozer-ingestion/oracle/src/connector/mapping.rs, dozer-ingestion/oracle/src/connector/mod.rs, dozer-ingestion/oracle/src/connector/replicate/listing.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/listing.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/mapping.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/mod.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/parse/delete.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/parse/insert.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/parse/mod.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/parse/row.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/parse/update.rs, dozer-ingestion/oracle/src/connector/replicate/merge.rs, dozer-ingestion/oracle/src/connector/replicate/mod.rs, dozer-ingestion/oracle/src/lib.rs, dozer-types/src/models/ingestion_types.rs, json_schemas/dozer.json
https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md#running-oracle-database-enterprise-and-standard-edition-2-in-a-container
After building the 19.3.0-ee docker image, run:
```bash
docker run --name oracle -p 1521:1521 -p 5500:5500 -e ORACLE_PWD=123 -e ENABLE_ARCHIVELOG=true -v ./data:/opt/oracle/oradata oracle/database:19.3.0-ee
```
First login as sysdba to the PDB:
```bash
./sqlplus sys/123@//localhost:1521/ORCLPDB1 as sysdba
```
Create a new user named `CHUBEI` (this is hardcoded in the test binary) and insert some data:
```sql
CREATE USER chubei IDENTIFIED BY 123;
GRANT CREATE SESSION TO chubei;
GRANT CREATE TABLE TO chubei;
ALTER USER CHUBEI QUOTA UNLIMITED ON USERS;
CREATE TABLE employees (
employee_id NUMBER,
first_name VARCHAR2(50),
last_name …
```
=> feat: Oracle replication

dozer-cli/src/cli/types.rs, dozer-cli/src/main.rs, dozer-cli/src/ui/app/mod.rs, dozer-cli/src/ui/app/state.rs, dozer-cli/src/ui/downloader.rs, dozer-cli/src/ui/mod.rs
updated CLI with 
`dozer ui`
`dozer ui update`
=> feat: dozer ui and dozer ui update

dozer-cli/src/pipeline/dummy_sink.rs, dozer-cli/src/pipeline/log_sink.rs, dozer-core/src/channels.rs, dozer-core/src/executor/execution_dag.rs, dozer-core/src/executor/mod.rs, dozer-core/src/executor/processor_node.rs, dozer-core/src/executor/receiver_loop.rs, dozer-core/src/executor/sink_node.rs, dozer-core/src/executor/source_node/mod.rs, dozer-core/src/executor_operation.rs, dozer-core/src/forwarder.rs, dozer-core/src/node.rs, dozer-core/src/tests/dag_base_errors.rs, dozer-core/src/tests/dag_base_run.rs, dozer-core/src/tests/sinks.rs, dozer-sink-aerospike/src/lib.rs, dozer-sink-clickhouse/src/lib.rs, dozer-sink-oracle/src/lib.rs, dozer-sql/src/aggregation/processor.rs, dozer-sql/src/expression/tests/test_common.rs, dozer-sql/src/product/join/processor.rs, dozer-sql/src/product/set/set_processor.rs, dozer-sql/src/product/table/processor.rs, dozer-sql/src/projection/processor.rs, dozer-sql/src/selection/processor.rs, dozer-sql/src/table_operator/processor.rs, dozer-sql/src/tests/builder_test.rs, dozer-sql/src/window/processor.rs, dozer-tests/src/sql_tests/helper/pipeline.rs, dozer-types/src/types/mod.rs
Based on https://github.com/getdozer/dozer/discussions/2387. Turns out that the "port concept" is still needed.
This PR changes how threads in the DAG talk to each other.
Previously if there are two edges between a pair of node, two channels are created and operations from the source node are split and sent to different channels, which loses the ordering of the operations.
In this PR we always use a single channel for node-to-node communication. The port information is hence moved into the `ExecutorOperation`.
This opens the possibility for implementing transaction-aware and order-preserving processors and sinks.
=> refactor: Guarentee operation order inside a transaction

dozer-sink-aerospike/src/lib.rs, dozer-types/src/models/endpoint.rs, json_schemas/dozer.json
Like before, if the name of a column (bin) is the same in both the
source set and destination set, you can specify it like
```yaml
columns:
- column_name
```
To rename, you can instead do
```yaml
columns:
- source: src_col
destination: dst_col
```
in which case the column will be looked up as `src_col` and written as
`dst_col`
=> Allow renaming of denormalized columns

dozer-ingestion/oracle/src/connector/mod.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/listing.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/mod.rs
Turns out we filtered redo records using `SCN`, which is the time that the change was made. We should filter using `COMMIT_SCN` instead.
@MrunmayS can you help validate that this fixes the bug?
=> fix: Oracle source skips uncommitted operations that are before another commit

dozer-ingestion/oracle/src/connector/mod.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/listing.rs, dozer-ingestion/oracle/src/connector/replicate/log_miner/parse/mod.rs
Not able to fix the spurious commit bug yet, but found another bug.
=> fix: Oracle redo log can have NULL REDO_SQL

.github/workflows/unit.yaml, Cargo.toml
Disable debuginfo in dev profile and remove MongoDB sidecar container
We can also disable debuginfo with an env var just for CI, but I think the
debuginfo _generally_ does not add too much value for us, and reducing build 
times and target dir size locally is a quite nice side benefit.
The `rust-cache` action already disables incremental compilation on CI, so
no need to also do that manually.
=> Reduce disk space usage in CI

Cargo.lock, dozer-core/src/builder_dag.rs, dozer-core/src/executor/mod.rs, dozer-core/src/node.rs, dozer-ingestion/oracle/src/connector/mod.rs, dozer-sink-aerospike/Cargo.toml, dozer-sink-aerospike/aerospike-client-sys/aerospike_client.h, dozer-sink-aerospike/aerospike-client-sys/src/lib.rs, dozer-sink-aerospike/src/aerospike.rs, dozer-sink-aerospike/src/denorm_dag.rs, dozer-sink-aerospike/src/lib.rs, dozer-types/src/models/sink.rs, dozer-types/src/types/field.rs, json_schemas/dozer.json
This is based on the aerospike resumability branch.
I added a configuration to the aerospike sink table config, which specifies
where to write the denormalized version of that table to, called `write_denormalized_to`.
All tables will also be written in their raw form.
Resumability is implemented using a two-phase approach:
First, write the denormalized tables, then write a txid for the denorm tables
Second, write the lookup tables, then write a txid for the lookup tables
If we go down between writing the denorm txid and the lookup txid, we skip denorm until we reach the lookup txid.
=> Aerospike sink: Add transactionally consistent denormalization

dozer-sink-clickhouse/src/client.rs, dozer-sink-clickhouse/src/errors.rs, dozer-sink-clickhouse/src/schema.rs, dozer-sink-clickhouse/src/sink.rs, dozer-sink-clickhouse/src/types.rs
Also replaced two big macros with a small one and avoided the cloning of the whole batch upon commit.
=> fix: Clickhouse conversion of `Null`, `Text` and `Decimal`

dozer-ingestion/postgres/src/schema/helper.rs, dozer-ingestion/postgres/src/schema/sorter.rs, dozer-ingestion/postgres/src/schema/tests.rs
These changes allows dozer to read schema and capture all errors in it.
=> fix: Fix error handling in postgres schema

dozer-ingestion/oracle/src/connector/mod.rs, dozer-ingestion/oracle/src/connector/replicate/log/mod.rs, dozer-ingestion/oracle/src/connector/replicate/log/redo/log_miner.rs, dozer-ingestion/oracle/src/connector/replicate/log/redo/mod.rs
This PR removes the filter on RBA columns, and optionally loads OPERATION_CODE filter from an env var called `DOZER_ORACLE_LOG_MINER_OPERATION_CODE_FILTER`.
Usage is like:
```bash
DOZER_ORACLE_LOG_MINER_OPERATION_CODE_FILTER='OPERATION_CODE in (1, 7)' cargo run
```
=> fix: Don't filter oracle V$LOG by rba
